/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.accupicks.client;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Ronnie
 */
public class CreateTournament extends javax.swing.JFrame {
JLabel background = new JLabel();
    /**
     * Creates new form CreateTournament
     */
    public CreateTournament() {
        initComponents();
        
        setLayout(new BorderLayout());
        ImageIcon imageIcon = new ImageIcon("../AccuPicks3.0/src/Resources/SoccerBackground.jpg"); 
        Image image = imageIcon.getImage(); 
        Image newimg = image.getScaledInstance(1366, 768,  java.awt.Image.SCALE_SMOOTH); 
        imageIcon = new ImageIcon(newimg); 
        background.setIcon(imageIcon);
        background.setText("");
	add(background);
	background.setLayout(new FlowLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CreateTournament = new javax.swing.JButton();
        OptimizedForCmb = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TournamentNameTxf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setOpaque(false);

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Create Tournament");

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("AccountName");

        CreateTournament.setBackground(new java.awt.Color(51, 51, 51));
        CreateTournament.setForeground(new java.awt.Color(255, 255, 255));
        CreateTournament.setText("Create Tournament");
        CreateTournament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateTournamentActionPerformed(evt);
            }
        });

        OptimizedForCmb.setBackground(new java.awt.Color(51, 51, 51));
        OptimizedForCmb.setForeground(new java.awt.Color(255, 255, 255));
        OptimizedForCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Soccer", "Cricket", "Rugby", "Netball", "Hockey", "Counter-Strike: Global Offensive", "League of Legends", "Dota 2" }));
        OptimizedForCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptimizedForCmbActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Optimized For:");

        jLabel19.setFont(new java.awt.Font("Algerian", 1, 60)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("AccuPicks");

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tournament Name:");

        TournamentNameTxf.setBackground(new java.awt.Color(51, 51, 51));
        TournamentNameTxf.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jLabel19))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CreateTournament, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OptimizedForCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TournamentNameTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TournamentNameTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OptimizedForCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(CreateTournament, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateTournamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateTournamentActionPerformed
        /*String TournamentName = TournamentNameTxf.getText();
        String Sport = (String) OptimizedForCmb.getSelectedItem();

        Boolean success = (new File("C:\\Program Files\\AccuPicks\\Tournaments\\"+Sport+"\\")).mkdirs();*/
    }//GEN-LAST:event_CreateTournamentActionPerformed

    private void OptimizedForCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptimizedForCmbActionPerformed
        String Sport = (String) OptimizedForCmb.getSelectedItem();
        
        if(Sport.matches("Cricket")){
            ImageIcon imageIcon = new ImageIcon("../AccuPicks3.0/src/Resources/CricketBackground.jpg"); 
            Image image = imageIcon.getImage(); 
            Image newimg = image.getScaledInstance(1366, 768,  java.awt.Image.SCALE_SMOOTH); 
            imageIcon = new ImageIcon(newimg); 
            background.setIcon(imageIcon);
            background.setText("");
        }
        
        if(Sport.matches("Soccer")){
            ImageIcon imageIcon = new ImageIcon("../AccuPicks3.0/src/Resources/SoccerBackground.jpg"); 
            Image image = imageIcon.getImage(); 
            Image newimg = image.getScaledInstance(1366, 768,  java.awt.Image.SCALE_SMOOTH); 
            imageIcon = new ImageIcon(newimg); 
            background.setIcon(imageIcon);
            background.setText("");
        }
        
        if(Sport.matches("Rugby")){
            ImageIcon imageIcon = new ImageIcon("../AccuPicks3.0/src/Resources/RugbyBackground.png"); 
            Image image = imageIcon.getImage(); 
            Image newimg = image.getScaledInstance(1366, 768,  java.awt.Image.SCALE_SMOOTH); 
            imageIcon = new ImageIcon(newimg); 
            background.setIcon(imageIcon);
            background.setText("");
        }
        
        if(Sport.matches("Netball")){
            ImageIcon imageIcon = new ImageIcon("../AccuPicks3.0/src/Resources/NetballBackground.gif"); 
            Image image = imageIcon.getImage(); 
            Image newimg = image.getScaledInstance(1366, 768,  java.awt.Image.SCALE_SMOOTH); 
            imageIcon = new ImageIcon(newimg); 
            background.setIcon(imageIcon);
            background.setText("");
        }
        
        if(Sport.matches("Hockey")){
            ImageIcon imageIcon = new ImageIcon("../AccuPicks3.0/src/Resources/HockeyBackground.jpg"); 
            Image image = imageIcon.getImage();
            Image newimg = image.getScaledInstance(1366, 768,  java.awt.Image.SCALE_SMOOTH); 
            imageIcon = new ImageIcon(newimg); 
            background.setIcon(imageIcon);
            background.setText("");
        }
        
        if(Sport.matches("Counter-Strike: Global Offensive")){
            ImageIcon imageIcon = new ImageIcon("../AccuPicks3.0/src/Resources/CSGOBackground.jpg"); 
            Image image = imageIcon.getImage(); 
            Image newimg = image.getScaledInstance(1366, 768,  java.awt.Image.SCALE_SMOOTH); 
            imageIcon = new ImageIcon(newimg); 
            background.setIcon(imageIcon);
            background.setText("");
        }
        
        if(Sport.matches("League of Legends")){
            ImageIcon imageIcon = new ImageIcon("../AccuPicks3.0/src/Resources/LeagueOfLegendsBackground.jpg"); 
            Image image = imageIcon.getImage(); 
            Image newimg = image.getScaledInstance(1366, 768,  java.awt.Image.SCALE_SMOOTH); 
            imageIcon = new ImageIcon(newimg); 
            background.setIcon(imageIcon);
            background.setText("");
        }
        
        if(Sport.matches("Dota 2")){
            ImageIcon imageIcon = new ImageIcon("../AccuPicks3.0/src/Resources/Dota2Background.jpg"); 
            Image image = imageIcon.getImage(); 
            Image newimg = image.getScaledInstance(1366, 768,  java.awt.Image.SCALE_SMOOTH); 
            imageIcon = new ImageIcon(newimg); 
            background.setIcon(imageIcon);
            background.setText("");
        }
    }//GEN-LAST:event_OptimizedForCmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTournament().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateTournament;
    private javax.swing.JComboBox OptimizedForCmb;
    private javax.swing.JTextField TournamentNameTxf;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
