/*
 * Sport score preditcion software
 * by Ronnie Muller & Stephan Malan
 */
package com.accupicks.client;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Ronnie
 */
public class CricketSetPositions extends javax.swing.JDialog {
JLabel backgroundLbl = new JLabel();
    /**
     * Creates new form CricketSetPositions
     */
    public CricketSetPositions(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        
        setLayout(new BorderLayout());
        add(backgroundLbl);
        backgroundLbl.setIcon(new ImageIcon(new ImageIcon(AdminHome.class.getResource("/resources/CricketBackground.jpg")).getImage().getScaledInstance(1366, 768, java.awt.Image.SCALE_SMOOTH)));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        CricketHeaderLbl = new javax.swing.JLabel();
        SetPositionsBtn = new javax.swing.JButton();
        Batsman4HeaderLbl = new javax.swing.JLabel();
        BatFirstCmb = new javax.swing.JComboBox();
        BowlFirstCmb = new javax.swing.JComboBox();
        SetPositionsHeaderLbl = new javax.swing.JLabel();
        Batsman10HeaderLbl = new javax.swing.JLabel();
        AccuPicksHeaderLbl = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        BowlFirstCmb1 = new javax.swing.JComboBox();
        Batsman6HeaderLbl = new javax.swing.JLabel();
        Batsman2HeaderLbl = new javax.swing.JLabel();
        BatFirstCmb1 = new javax.swing.JComboBox();
        Batsman11HeaderLbl = new javax.swing.JLabel();
        BatFirstCmb2 = new javax.swing.JComboBox();
        Batsman9HeaderLbl = new javax.swing.JLabel();
        BatFirstCmb3 = new javax.swing.JComboBox();
        BatFirstCmb4 = new javax.swing.JComboBox();
        Batsman8HeaderLbl = new javax.swing.JLabel();
        BatFirstCmb5 = new javax.swing.JComboBox();
        Batsman1HeaderLbl = new javax.swing.JLabel();
        Batsman3HeaderLbl = new javax.swing.JLabel();
        BatFirstCmb6 = new javax.swing.JComboBox();
        Batsman5HeaderLbl = new javax.swing.JLabel();
        BatFirstCmb8 = new javax.swing.JComboBox();
        BatFirstCmb9 = new javax.swing.JComboBox();
        Batsman7HeaderLbl = new javax.swing.JLabel();
        BatFirstCmb10 = new javax.swing.JComboBox();
        Batsman12HeaderLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(51, 51, 51));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        MainPanel.setOpaque(false);

        CricketHeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        CricketHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        CricketHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        CricketHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CricketHeaderLbl.setText("Cricket");

        SetPositionsBtn.setBackground(new java.awt.Color(51, 51, 51));
        SetPositionsBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        SetPositionsBtn.setForeground(new java.awt.Color(255, 255, 255));
        SetPositionsBtn.setText("Set Positions");
        SetPositionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetPositionsBtnActionPerformed(evt);
            }
        });

        Batsman4HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Batsman4HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Batsman4HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Batsman4HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Batsman4HeaderLbl.setText("4th Batsman:");

        BatFirstCmb.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstCmb.setForeground(new java.awt.Color(255, 255, 255));

        BowlFirstCmb.setBackground(new java.awt.Color(51, 51, 51));
        BowlFirstCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BowlFirstCmb.setForeground(new java.awt.Color(255, 255, 255));

        SetPositionsHeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        SetPositionsHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        SetPositionsHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        SetPositionsHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SetPositionsHeaderLbl.setText("Set Positions");

        Batsman10HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Batsman10HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Batsman10HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Batsman10HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Batsman10HeaderLbl.setText("10th Batsman:");

        AccuPicksHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 60)); // NOI18N
        AccuPicksHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        AccuPicksHeaderLbl.setText("AccuPicks");

        BackBtn.setBackground(new java.awt.Color(51, 51, 51));
        BackBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        BowlFirstCmb1.setBackground(new java.awt.Color(51, 51, 51));
        BowlFirstCmb1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BowlFirstCmb1.setForeground(new java.awt.Color(255, 255, 255));

        Batsman6HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Batsman6HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Batsman6HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Batsman6HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Batsman6HeaderLbl.setText("6th Batsman:");

        Batsman2HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Batsman2HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Batsman2HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Batsman2HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Batsman2HeaderLbl.setText("2nd Batsman:");

        BatFirstCmb1.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstCmb1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstCmb1.setForeground(new java.awt.Color(255, 255, 255));

        Batsman11HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Batsman11HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Batsman11HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Batsman11HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Batsman11HeaderLbl.setText("11th Batsman:");

        BatFirstCmb2.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstCmb2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstCmb2.setForeground(new java.awt.Color(255, 255, 255));

        Batsman9HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Batsman9HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Batsman9HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Batsman9HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Batsman9HeaderLbl.setText("9th Batsman:");

        BatFirstCmb3.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstCmb3.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstCmb3.setForeground(new java.awt.Color(255, 255, 255));

        BatFirstCmb4.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstCmb4.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstCmb4.setForeground(new java.awt.Color(255, 255, 255));

        Batsman8HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Batsman8HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Batsman8HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Batsman8HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Batsman8HeaderLbl.setText("8th Batsman:");

        BatFirstCmb5.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstCmb5.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstCmb5.setForeground(new java.awt.Color(255, 255, 255));

        Batsman1HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Batsman1HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Batsman1HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Batsman1HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Batsman1HeaderLbl.setText("1st Batsman:");

        Batsman3HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Batsman3HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Batsman3HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Batsman3HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Batsman3HeaderLbl.setText("3rd Batsman:");

        BatFirstCmb6.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstCmb6.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstCmb6.setForeground(new java.awt.Color(255, 255, 255));

        Batsman5HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Batsman5HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Batsman5HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Batsman5HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Batsman5HeaderLbl.setText("5th Batsman:");

        BatFirstCmb8.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstCmb8.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstCmb8.setForeground(new java.awt.Color(255, 255, 255));

        BatFirstCmb9.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstCmb9.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstCmb9.setForeground(new java.awt.Color(255, 255, 255));

        Batsman7HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Batsman7HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Batsman7HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Batsman7HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Batsman7HeaderLbl.setText("7th Batsman:");

        BatFirstCmb10.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstCmb10.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstCmb10.setForeground(new java.awt.Color(255, 255, 255));

        Batsman12HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Batsman12HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Batsman12HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Batsman12HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Batsman12HeaderLbl.setText("12th Man:");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AccuPicksHeaderLbl)
                .addGap(497, 497, 497))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(594, 594, 594)
                        .addComponent(CricketHeaderLbl))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(610, 610, 610)
                        .addComponent(SetPositionsHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(1022, 1022, 1022)
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SetPositionsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Batsman5HeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Batsman7HeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Batsman9HeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Batsman11HeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Batsman3HeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Batsman1HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BatFirstCmb4, 0, 330, Short.MAX_VALUE)
                            .addComponent(BatFirstCmb5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BatFirstCmb6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BatFirstCmb3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BatFirstCmb8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BatFirstCmb9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Batsman10HeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Batsman12HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Batsman2HeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(Batsman4HeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Batsman6HeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Batsman8HeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BatFirstCmb, 0, 330, Short.MAX_VALUE)
                            .addComponent(BatFirstCmb1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BowlFirstCmb1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BatFirstCmb2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BowlFirstCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BatFirstCmb10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(AccuPicksHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CricketHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SetPositionsHeaderLbl)
                .addGap(57, 57, 57)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BatFirstCmb4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatFirstCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Batsman1HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Batsman2HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BatFirstCmb5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatFirstCmb1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Batsman3HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Batsman4HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BatFirstCmb6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BowlFirstCmb1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Batsman5HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Batsman6HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BatFirstCmb3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatFirstCmb2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Batsman7HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Batsman8HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BatFirstCmb8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BowlFirstCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Batsman9HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Batsman10HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BatFirstCmb9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Batsman11HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatFirstCmb10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Batsman12HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(SetPositionsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SetPositionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetPositionsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SetPositionsBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        //new LiveScoreKeepingHome(CLIENT).setVisible(true);
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CricketSetPositions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CricketSetPositions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CricketSetPositions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CricketSetPositions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CricketSetPositions dialog = new CricketSetPositions(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccuPicksHeaderLbl;
    private javax.swing.JButton BackBtn;
    private javax.swing.JComboBox BatFirstCmb;
    private javax.swing.JComboBox BatFirstCmb1;
    private javax.swing.JComboBox BatFirstCmb10;
    private javax.swing.JComboBox BatFirstCmb2;
    private javax.swing.JComboBox BatFirstCmb3;
    private javax.swing.JComboBox BatFirstCmb4;
    private javax.swing.JComboBox BatFirstCmb5;
    private javax.swing.JComboBox BatFirstCmb6;
    private javax.swing.JComboBox BatFirstCmb8;
    private javax.swing.JComboBox BatFirstCmb9;
    private javax.swing.JLabel Batsman10HeaderLbl;
    private javax.swing.JLabel Batsman11HeaderLbl;
    private javax.swing.JLabel Batsman12HeaderLbl;
    private javax.swing.JLabel Batsman1HeaderLbl;
    private javax.swing.JLabel Batsman2HeaderLbl;
    private javax.swing.JLabel Batsman3HeaderLbl;
    private javax.swing.JLabel Batsman4HeaderLbl;
    private javax.swing.JLabel Batsman5HeaderLbl;
    private javax.swing.JLabel Batsman6HeaderLbl;
    private javax.swing.JLabel Batsman7HeaderLbl;
    private javax.swing.JLabel Batsman8HeaderLbl;
    private javax.swing.JLabel Batsman9HeaderLbl;
    private javax.swing.JComboBox BowlFirstCmb;
    private javax.swing.JComboBox BowlFirstCmb1;
    private javax.swing.JLabel CricketHeaderLbl;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton SetPositionsBtn;
    private javax.swing.JLabel SetPositionsHeaderLbl;
    // End of variables declaration//GEN-END:variables
}
