/*
 * Sport score preditcion software
 * by Ronnie Muller & Stephan Malan
 */
package com.accupicks.client;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronnie
 */
public class CricketLiveScoreKeepingGameData extends javax.swing.JFrame {
JLabel background = new JLabel();
    /**
     * Creates new form CricketLiveScoreKeepingGameData
     */
    public CricketLiveScoreKeepingGameData() {
        initComponents();
        
        setLayout(new BorderLayout());
	JLabel background=new JLabel(new ImageIcon("../AccuPicks/src/resources/CricketBackground.jpg"));
	add(background);
	background.setLayout(new FlowLayout());
        
        //tabbedpane and labels to team name
    }

        public void addBalls(){
        int Overs = Integer.parseInt(Team1OversLbl.getText().substring(0, Team1OversLbl.getText().indexOf(".")));
        int Balls = Integer.parseInt(Team1OversLbl.getText().substring(Team1OversLbl.getText().indexOf(".")+1,Team1OversLbl.getText().length()));
        if(Balls<5){
            Balls++;
            Team1OversLbl.setText(Integer.toString(Overs)+"."+Integer.toString(Balls));
        }else{
            Overs++;
            Balls = 0;
            Team1OversLbl.setText(Integer.toString(Overs)+"."+Integer.toString(Balls));
            JOptionPane.showMessageDialog(null, "End of Over");
        }    
    }

    public void swapStrikersEnd(){
        if(StrikersEndLbl.getText().matches(Batsman1Lbl.getText())){
            StrikersEndLbl.setText(Batsman2Lbl.getText());
        }else{
            StrikersEndLbl.setText(Batsman1Lbl.getText());
        }   
    }

    public void battingStrikersEnd(int Runs){
        switch (Runs) {
            case 1:  swapStrikersEnd();
                     break;
            case 3:  swapStrikersEnd();
                     break;
            case 5:  swapStrikersEnd();
                     break;
            default: break;
        }
}

    public void addRuns(int Runs,boolean wide){
        int CurRuns = Integer.parseInt(Team1ScoreLbl.getText().substring(0, Team1ScoreLbl.getText().indexOf("-")));
        int Wickets = Integer.parseInt(Team1ScoreLbl.getText().substring(Team1ScoreLbl.getText().indexOf("-")+1,Team1ScoreLbl.getText().length()));
        Team1ScoreLbl.setText(Integer.toString(CurRuns+Runs)+"-"+Integer.toString(Wickets));
        if(wide==false){
            addBalls();
            battingStrikersEnd(Runs);
        }    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        AccountNameLbl = new javax.swing.JLabel();
        LiveScoreKeepingHeaderLbl = new javax.swing.JLabel();
        CricketHeaderLbl = new javax.swing.JLabel();
        Team1Panel = new javax.swing.JPanel();
        Team1Lbl = new javax.swing.JLabel();
        Team1ScoreLbl = new javax.swing.JLabel();
        Team1OversLbl = new javax.swing.JLabel();
        Team1OversHeaderLbl = new javax.swing.JLabel();
        Team1ScoreHeaderLbl = new javax.swing.JLabel();
        Team2Panel = new javax.swing.JPanel();
        Team2Lbl = new javax.swing.JLabel();
        Team2ScoreLbl = new javax.swing.JLabel();
        Team2OversLbl = new javax.swing.JLabel();
        Team2OversHeaderLbl = new javax.swing.JLabel();
        Team2ScoreHeaderLbl = new javax.swing.JLabel();
        BatsmenLbl = new javax.swing.JLabel();
        Batsman1Lbl = new javax.swing.JLabel();
        Batsman2Lbl = new javax.swing.JLabel();
        BowlerHeaderLbl = new javax.swing.JLabel();
        BowlerLbl = new javax.swing.JLabel();
        StrikersEndHeaderLbl = new javax.swing.JLabel();
        StrikersEndLbl = new javax.swing.JLabel();
        StatsTabbedPane = new javax.swing.JTabbedPane();
        Team1BattingStatsTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Team1BattingStatsTbl = new javax.swing.JTable();
        Team1BowlingStatsTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Team1BowlingStatsTbl = new javax.swing.JTable();
        Team2BattingStatsTab = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Team2BattingStatsTbl = new javax.swing.JTable();
        Team2BowlingStatsTab = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Team2BowlingStatsTbl = new javax.swing.JTable();
        AddRunsPanel = new javax.swing.JPanel();
        ZeroRunsBtn = new javax.swing.JButton();
        SixRunsBtn = new javax.swing.JButton();
        FourRunsBtn = new javax.swing.JButton();
        AddRunsBtn = new javax.swing.JButton();
        WideNoBallPanel = new javax.swing.JPanel();
        NoBallBtn = new javax.swing.JButton();
        WideBallBtn = new javax.swing.JButton();
        WicketPanel = new javax.swing.JPanel();
        WicketBtn = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        AccuPicksHeaderLbl = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(51, 51, 51));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        MainPanel.setOpaque(false);

        AccountNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        AccountNameLbl.setText("AccountName");

        LiveScoreKeepingHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        LiveScoreKeepingHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        LiveScoreKeepingHeaderLbl.setText("Live score keeping");

        CricketHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        CricketHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        CricketHeaderLbl.setText("Cricket");

        Team1Panel.setBackground(new java.awt.Color(51, 51, 51));
        Team1Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Team1Panel.setOpaque(false);

        Team1Lbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        Team1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        Team1Lbl.setText("Team 1");

        Team1ScoreLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Team1ScoreLbl.setForeground(new java.awt.Color(255, 255, 255));
        Team1ScoreLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team1ScoreLbl.setText("0-0");

        Team1OversLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Team1OversLbl.setForeground(new java.awt.Color(255, 255, 255));
        Team1OversLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team1OversLbl.setText("0.0");

        Team1OversHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Team1OversHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Team1OversHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Team1OversHeaderLbl.setText("Overs:");

        Team1ScoreHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Team1ScoreHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Team1ScoreHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Team1ScoreHeaderLbl.setText("Score:");

        javax.swing.GroupLayout Team1PanelLayout = new javax.swing.GroupLayout(Team1Panel);
        Team1Panel.setLayout(Team1PanelLayout);
        Team1PanelLayout.setHorizontalGroup(
            Team1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Team1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Team1OversHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(Team1ScoreHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Team1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Team1ScoreLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Team1OversLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Team1PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Team1Lbl)
                .addGap(20, 20, 20))
        );
        Team1PanelLayout.setVerticalGroup(
            Team1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Team1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Team1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Team1ScoreLbl)
                    .addComponent(Team1ScoreHeaderLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Team1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Team1OversHeaderLbl)
                    .addComponent(Team1OversLbl))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Team2Panel.setBackground(new java.awt.Color(51, 51, 51));
        Team2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Team2Panel.setOpaque(false);

        Team2Lbl.setBackground(new java.awt.Color(51, 51, 51));
        Team2Lbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        Team2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        Team2Lbl.setText("Team 2");

        Team2ScoreLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Team2ScoreLbl.setForeground(new java.awt.Color(255, 255, 255));
        Team2ScoreLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team2ScoreLbl.setText("0-0");

        Team2OversLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Team2OversLbl.setForeground(new java.awt.Color(255, 255, 255));
        Team2OversLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team2OversLbl.setText("0.0");

        Team2OversHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Team2OversHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Team2OversHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Team2OversHeaderLbl.setText("Overs:");

        Team2ScoreHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Team2ScoreHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Team2ScoreHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Team2ScoreHeaderLbl.setText("Score:");

        javax.swing.GroupLayout Team2PanelLayout = new javax.swing.GroupLayout(Team2Panel);
        Team2Panel.setLayout(Team2PanelLayout);
        Team2PanelLayout.setHorizontalGroup(
            Team2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Team2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Team2ScoreHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Team2OversHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Team2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Team2ScoreLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Team2OversLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Team2PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Team2Lbl)
                .addGap(20, 20, 20))
        );
        Team2PanelLayout.setVerticalGroup(
            Team2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Team2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Team2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Team2ScoreLbl)
                    .addComponent(Team2ScoreHeaderLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Team2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Team2OversHeaderLbl)
                    .addComponent(Team2OversLbl))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        BatsmenLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        BatsmenLbl.setForeground(new java.awt.Color(255, 255, 255));
        BatsmenLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BatsmenLbl.setText("Batsmen:");

        Batsman1Lbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Batsman1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        Batsman1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Batsman1Lbl.setText("Surname,Name1");

        Batsman2Lbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Batsman2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        Batsman2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Batsman2Lbl.setText("Surname,Name2");

        BowlerHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        BowlerHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        BowlerHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BowlerHeaderLbl.setText("Bowler:");

        BowlerLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        BowlerLbl.setForeground(new java.awt.Color(255, 255, 255));
        BowlerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BowlerLbl.setText("Surname,Name");

        StrikersEndHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        StrikersEndHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        StrikersEndHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        StrikersEndHeaderLbl.setText("Strikers end:");

        StrikersEndLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        StrikersEndLbl.setForeground(new java.awt.Color(255, 255, 255));
        StrikersEndLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StrikersEndLbl.setText("Surname,Name1");

        StatsTabbedPane.setBackground(new java.awt.Color(51, 51, 51));
        StatsTabbedPane.setForeground(new java.awt.Color(255, 255, 255));

        Team1BattingStatsTab.setBackground(new java.awt.Color(51, 51, 51));
        Team1BattingStatsTab.setOpaque(false);

        Team1BattingStatsTbl.setBackground(new java.awt.Color(51, 51, 51));
        Team1BattingStatsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Team1BattingStatsTbl);

        javax.swing.GroupLayout Team1BattingStatsTabLayout = new javax.swing.GroupLayout(Team1BattingStatsTab);
        Team1BattingStatsTab.setLayout(Team1BattingStatsTabLayout);
        Team1BattingStatsTabLayout.setHorizontalGroup(
            Team1BattingStatsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team1BattingStatsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1283, Short.MAX_VALUE)
                .addContainerGap())
        );
        Team1BattingStatsTabLayout.setVerticalGroup(
            Team1BattingStatsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team1BattingStatsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        StatsTabbedPane.addTab("Team 1 Batting Stats", Team1BattingStatsTab);

        Team1BowlingStatsTab.setBackground(new java.awt.Color(51, 51, 51));
        Team1BowlingStatsTab.setOpaque(false);

        Team1BowlingStatsTbl.setBackground(new java.awt.Color(51, 51, 51));
        Team1BowlingStatsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Team1BowlingStatsTbl);

        javax.swing.GroupLayout Team1BowlingStatsTabLayout = new javax.swing.GroupLayout(Team1BowlingStatsTab);
        Team1BowlingStatsTab.setLayout(Team1BowlingStatsTabLayout);
        Team1BowlingStatsTabLayout.setHorizontalGroup(
            Team1BowlingStatsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team1BowlingStatsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1283, Short.MAX_VALUE)
                .addContainerGap())
        );
        Team1BowlingStatsTabLayout.setVerticalGroup(
            Team1BowlingStatsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team1BowlingStatsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        StatsTabbedPane.addTab("Team 1 Bowling Stats", Team1BowlingStatsTab);

        Team2BattingStatsTab.setBackground(new java.awt.Color(51, 51, 51));
        Team2BattingStatsTab.setOpaque(false);

        Team2BattingStatsTbl.setBackground(new java.awt.Color(51, 51, 51));
        Team2BattingStatsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(Team2BattingStatsTbl);

        javax.swing.GroupLayout Team2BattingStatsTabLayout = new javax.swing.GroupLayout(Team2BattingStatsTab);
        Team2BattingStatsTab.setLayout(Team2BattingStatsTabLayout);
        Team2BattingStatsTabLayout.setHorizontalGroup(
            Team2BattingStatsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team2BattingStatsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1283, Short.MAX_VALUE)
                .addContainerGap())
        );
        Team2BattingStatsTabLayout.setVerticalGroup(
            Team2BattingStatsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team2BattingStatsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        StatsTabbedPane.addTab("Team 2 Batting Stats", Team2BattingStatsTab);

        Team2BowlingStatsTab.setBackground(new java.awt.Color(51, 51, 51));
        Team2BowlingStatsTab.setOpaque(false);

        jScrollPane4.setBackground(new java.awt.Color(51, 51, 51));

        Team2BowlingStatsTbl.setBackground(new java.awt.Color(51, 51, 51));
        Team2BowlingStatsTbl.setForeground(new java.awt.Color(255, 255, 255));
        Team2BowlingStatsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(Team2BowlingStatsTbl);

        javax.swing.GroupLayout Team2BowlingStatsTabLayout = new javax.swing.GroupLayout(Team2BowlingStatsTab);
        Team2BowlingStatsTab.setLayout(Team2BowlingStatsTabLayout);
        Team2BowlingStatsTabLayout.setHorizontalGroup(
            Team2BowlingStatsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team2BowlingStatsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1283, Short.MAX_VALUE)
                .addContainerGap())
        );
        Team2BowlingStatsTabLayout.setVerticalGroup(
            Team2BowlingStatsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team2BowlingStatsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        StatsTabbedPane.addTab("Team 2 Bowling Stats", Team2BowlingStatsTab);

        AddRunsPanel.setBackground(new java.awt.Color(51, 51, 51));
        AddRunsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        AddRunsPanel.setOpaque(false);

        ZeroRunsBtn.setBackground(new java.awt.Color(51, 51, 51));
        ZeroRunsBtn.setForeground(new java.awt.Color(255, 255, 255));
        ZeroRunsBtn.setText("0");
        ZeroRunsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroRunsBtnActionPerformed(evt);
            }
        });

        SixRunsBtn.setBackground(new java.awt.Color(51, 51, 51));
        SixRunsBtn.setForeground(new java.awt.Color(255, 255, 255));
        SixRunsBtn.setText("6");
        SixRunsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixRunsBtnActionPerformed(evt);
            }
        });

        FourRunsBtn.setBackground(new java.awt.Color(51, 51, 51));
        FourRunsBtn.setForeground(new java.awt.Color(255, 255, 255));
        FourRunsBtn.setText("4");
        FourRunsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourRunsBtnActionPerformed(evt);
            }
        });

        AddRunsBtn.setBackground(new java.awt.Color(51, 51, 51));
        AddRunsBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddRunsBtn.setText("+Runs");
        AddRunsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRunsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddRunsPanelLayout = new javax.swing.GroupLayout(AddRunsPanel);
        AddRunsPanel.setLayout(AddRunsPanelLayout);
        AddRunsPanelLayout.setHorizontalGroup(
            AddRunsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddRunsPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(AddRunsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FourRunsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(ZeroRunsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddRunsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddRunsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(SixRunsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddRunsPanelLayout.setVerticalGroup(
            AddRunsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddRunsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddRunsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ZeroRunsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(AddRunsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddRunsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FourRunsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(SixRunsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        WideNoBallPanel.setBackground(new java.awt.Color(51, 51, 51));
        WideNoBallPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        WideNoBallPanel.setOpaque(false);

        NoBallBtn.setBackground(new java.awt.Color(51, 51, 51));
        NoBallBtn.setForeground(new java.awt.Color(255, 255, 255));
        NoBallBtn.setText("No Ball");
        NoBallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoBallBtnActionPerformed(evt);
            }
        });

        WideBallBtn.setBackground(new java.awt.Color(51, 51, 51));
        WideBallBtn.setForeground(new java.awt.Color(255, 255, 255));
        WideBallBtn.setText("Wide");
        WideBallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WideBallBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WideNoBallPanelLayout = new javax.swing.GroupLayout(WideNoBallPanel);
        WideNoBallPanel.setLayout(WideNoBallPanelLayout);
        WideNoBallPanelLayout.setHorizontalGroup(
            WideNoBallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WideNoBallPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WideBallBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(NoBallBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        WideNoBallPanelLayout.setVerticalGroup(
            WideNoBallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WideNoBallPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WideNoBallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoBallBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WideBallBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        WicketPanel.setBackground(new java.awt.Color(51, 51, 51));
        WicketPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        WicketPanel.setOpaque(false);

        WicketBtn.setBackground(new java.awt.Color(51, 51, 51));
        WicketBtn.setForeground(new java.awt.Color(255, 255, 255));
        WicketBtn.setText("Wicket");
        WicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WicketBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WicketPanelLayout = new javax.swing.GroupLayout(WicketPanel);
        WicketPanel.setLayout(WicketPanelLayout);
        WicketPanelLayout.setHorizontalGroup(
            WicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WicketPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(WicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        WicketPanelLayout.setVerticalGroup(
            WicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WicketPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel12.setOpaque(false);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );

        AccuPicksHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 60)); // NOI18N
        AccuPicksHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        AccuPicksHeaderLbl.setText("AccuPicks");

        BackBtn.setBackground(new java.awt.Color(51, 51, 51));
        BackBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StatsTabbedPane)
                .addContainerGap())
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Team1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddRunsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(WideNoBallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WicketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(CricketHeaderLbl)
                                .addGap(272, 272, 272))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BatsmenLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BowlerHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StrikersEndHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BowlerLbl)
                                    .addComponent(StrikersEndLbl)
                                    .addComponent(Batsman1Lbl)
                                    .addComponent(Batsman2Lbl))
                                .addGap(257, 257, 257))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(LiveScoreKeepingHeaderLbl)
                                .addGap(297, 297, 297))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(AccountNameLbl)
                                .addGap(340, 340, 340)))))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Team2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(AccuPicksHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(AccuPicksHeaderLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CricketHeaderLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LiveScoreKeepingHeaderLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccountNameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StrikersEndLbl)
                            .addComponent(StrikersEndHeaderLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BowlerLbl)
                            .addComponent(BowlerHeaderLbl))
                        .addGap(12, 12, 12))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Team2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Team1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Batsman1Lbl)
                            .addComponent(BatsmenLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(Batsman2Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(WideNoBallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WicketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(AddRunsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(StatsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ZeroRunsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroRunsBtnActionPerformed
        addRuns(0,false);
    }//GEN-LAST:event_ZeroRunsBtnActionPerformed

    private void SixRunsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixRunsBtnActionPerformed
        addRuns(6,false);
    }//GEN-LAST:event_SixRunsBtnActionPerformed

    private void FourRunsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourRunsBtnActionPerformed
        addRuns(4,false);
    }//GEN-LAST:event_FourRunsBtnActionPerformed

    private void AddRunsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRunsBtnActionPerformed
        int Runs = Integer.parseInt(JOptionPane.showInputDialog("Runs?"));
        addRuns(Runs,false);
    }//GEN-LAST:event_AddRunsBtnActionPerformed

    private void WideBallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WideBallBtnActionPerformed
        addRuns(1,true);
    }//GEN-LAST:event_WideBallBtnActionPerformed

    private void NoBallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoBallBtnActionPerformed
        int Runs = Integer.parseInt(JOptionPane.showInputDialog("Runs?"));
        addRuns(Runs,false);
    }//GEN-LAST:event_NoBallBtnActionPerformed

    private void WicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WicketBtnActionPerformed
        int CurRuns = Integer.parseInt(Team1ScoreLbl.getText().substring(0, Team1ScoreLbl.getText().indexOf("-")));
        int Wickets = Integer.parseInt(Team1ScoreLbl.getText().substring(Team1ScoreLbl.getText().indexOf("-")+1,Team1ScoreLbl.getText().length()));
        Team1ScoreLbl.setText(Integer.toString(CurRuns)+"-"+Integer.toString(Wickets+1));
        //swap Batsman
        //if end of game or half else
    }//GEN-LAST:event_WicketBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        new CricketLiveScoreKeepingInfo().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CricketLiveScoreKeepingGameData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CricketLiveScoreKeepingGameData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CricketLiveScoreKeepingGameData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CricketLiveScoreKeepingGameData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CricketLiveScoreKeepingGameData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNameLbl;
    private javax.swing.JLabel AccuPicksHeaderLbl;
    private javax.swing.JButton AddRunsBtn;
    private javax.swing.JPanel AddRunsPanel;
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel Batsman1Lbl;
    private javax.swing.JLabel Batsman2Lbl;
    private javax.swing.JLabel BatsmenLbl;
    private javax.swing.JLabel BowlerHeaderLbl;
    private javax.swing.JLabel BowlerLbl;
    private javax.swing.JLabel CricketHeaderLbl;
    private javax.swing.JButton FourRunsBtn;
    private javax.swing.JLabel LiveScoreKeepingHeaderLbl;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton NoBallBtn;
    private javax.swing.JButton SixRunsBtn;
    private javax.swing.JTabbedPane StatsTabbedPane;
    private javax.swing.JLabel StrikersEndHeaderLbl;
    private javax.swing.JLabel StrikersEndLbl;
    private javax.swing.JPanel Team1BattingStatsTab;
    private javax.swing.JTable Team1BattingStatsTbl;
    private javax.swing.JPanel Team1BowlingStatsTab;
    private javax.swing.JTable Team1BowlingStatsTbl;
    private javax.swing.JLabel Team1Lbl;
    private javax.swing.JLabel Team1OversHeaderLbl;
    private javax.swing.JLabel Team1OversLbl;
    private javax.swing.JPanel Team1Panel;
    private javax.swing.JLabel Team1ScoreHeaderLbl;
    private javax.swing.JLabel Team1ScoreLbl;
    private javax.swing.JPanel Team2BattingStatsTab;
    private javax.swing.JTable Team2BattingStatsTbl;
    private javax.swing.JPanel Team2BowlingStatsTab;
    private javax.swing.JTable Team2BowlingStatsTbl;
    private javax.swing.JLabel Team2Lbl;
    private javax.swing.JLabel Team2OversHeaderLbl;
    private javax.swing.JLabel Team2OversLbl;
    private javax.swing.JPanel Team2Panel;
    private javax.swing.JLabel Team2ScoreHeaderLbl;
    private javax.swing.JLabel Team2ScoreLbl;
    private javax.swing.JButton WicketBtn;
    private javax.swing.JPanel WicketPanel;
    private javax.swing.JButton WideBallBtn;
    private javax.swing.JPanel WideNoBallPanel;
    private javax.swing.JButton ZeroRunsBtn;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
