/*
 * Sport score preditcion software
 * by Ronnie Muller & Stephan Malan
 */
package com.accupicks.client;

import com.shared.Client;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Ronnie
 */
public class LiveScoreKeepingHome extends javax.swing.JFrame {
JLabel backgroundLbl = new JLabel();
private final Client CLIENT;
    /**
     * Creates new form LiveScoreKeepingHome
     */
    public LiveScoreKeepingHome(Client client) {
        CLIENT = client;
        initComponents();
        
        setLocationRelativeTo(null);
        AccountNameLbl.setText(CLIENT.getName());
        
        setLayout(new BorderLayout());
        add(backgroundLbl);
        backgroundLbl.setIcon(new ImageIcon(new ImageIcon(AdminHome.class.getResource("/resources/HomeBackground1.jpg")).getImage().getScaledInstance(1366, 768, java.awt.Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SportTabbedPane = new javax.swing.JTabbedPane();
        CricketPane = new javax.swing.JPanel();
        CricketHeaderLbl = new javax.swing.JLabel();
        CricketMatchCmb = new javax.swing.JComboBox();
        CricketGoToMatchBtn = new javax.swing.JButton();
        CricketMatchLbl = new javax.swing.JLabel();
        RugbyPane = new javax.swing.JPanel();
        RugbyHeaderLbl = new javax.swing.JLabel();
        RugbyMatchCmb = new javax.swing.JComboBox();
        RugbyGoToMatchBtn = new javax.swing.JButton();
        RugbyMatchLbl = new javax.swing.JLabel();
        SoccerPane = new javax.swing.JPanel();
        SoccerHeaderLbl = new javax.swing.JLabel();
        SoccerMatchCmb = new javax.swing.JComboBox();
        SoccerGoToMatchBtn = new javax.swing.JButton();
        SoccerMatchLbl = new javax.swing.JLabel();
        AmericanFootballPane = new javax.swing.JPanel();
        AmericanFootballHeaderLbl = new javax.swing.JLabel();
        AmericanFootballMatchCmb = new javax.swing.JComboBox();
        AmericanFootballGoToMatchBtn = new javax.swing.JButton();
        AmericanFootballMatchLbl = new javax.swing.JLabel();
        BasketballPane = new javax.swing.JPanel();
        BasketballHeaderLbl = new javax.swing.JLabel();
        BasketballMatchCmb = new javax.swing.JComboBox();
        BasketballGoToMatchBtn = new javax.swing.JButton();
        BasketballMatchLbl = new javax.swing.JLabel();
        CSGOPane = new javax.swing.JPanel();
        CSGOHeaderLbl = new javax.swing.JLabel();
        CSGOMatchCmb = new javax.swing.JComboBox();
        CSGOGoToMatchBtn = new javax.swing.JButton();
        CSGOMatchLbl = new javax.swing.JLabel();
        LoLPane = new javax.swing.JPanel();
        LoLHeaderLbl = new javax.swing.JLabel();
        LoLMatchCmb = new javax.swing.JComboBox();
        LoLGoToMatchBtn = new javax.swing.JButton();
        LoLMatchLbl = new javax.swing.JLabel();
        Dota2Pane = new javax.swing.JPanel();
        Dota2HeaderLbl = new javax.swing.JLabel();
        Dota2MatchCmb = new javax.swing.JComboBox();
        Dota2GoToMatchBtn = new javax.swing.JButton();
        Dota2MatchLbl = new javax.swing.JLabel();
        AccuPicksHeaderLbl = new javax.swing.JLabel();
        LiveScoreKeepingLbl = new javax.swing.JLabel();
        AccountNameLbl = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        MainPanel.setOpaque(false);

        SportTabbedPane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SportTabbedPaneKeyPressed(evt);
            }
        });

        CricketPane.setBackground(new java.awt.Color(51, 51, 51));
        CricketPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        CricketPane.setOpaque(false);

        CricketHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        CricketHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CricketHeaderLbl.setText("Cricket");

        CricketMatchCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        CricketGoToMatchBtn.setBackground(new java.awt.Color(51, 51, 51));
        CricketGoToMatchBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        CricketGoToMatchBtn.setText("Go To Match");
        CricketGoToMatchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CricketGoToMatchBtnActionPerformed(evt);
            }
        });

        CricketMatchLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        CricketMatchLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CricketMatchLbl.setText("Match:");

        javax.swing.GroupLayout CricketPaneLayout = new javax.swing.GroupLayout(CricketPane);
        CricketPane.setLayout(CricketPaneLayout);
        CricketPaneLayout.setHorizontalGroup(
            CricketPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CricketPaneLayout.createSequentialGroup()
                .addGroup(CricketPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CricketPaneLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addGroup(CricketPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CricketGoToMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CricketPaneLayout.createSequentialGroup()
                                .addComponent(CricketMatchLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CricketMatchCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CricketPaneLayout.createSequentialGroup()
                        .addGap(498, 498, 498)
                        .addComponent(CricketHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        CricketPaneLayout.setVerticalGroup(
            CricketPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CricketPaneLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(CricketHeaderLbl)
                .addGap(76, 76, 76)
                .addGroup(CricketPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CricketMatchCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CricketMatchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109)
                .addComponent(CricketGoToMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );

        SportTabbedPane.addTab("Cricket", CricketPane);

        RugbyPane.setBackground(new java.awt.Color(51, 51, 51));
        RugbyPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        RugbyPane.setOpaque(false);

        RugbyHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        RugbyHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RugbyHeaderLbl.setText("Rugby");

        RugbyMatchCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        RugbyGoToMatchBtn.setBackground(new java.awt.Color(51, 51, 51));
        RugbyGoToMatchBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RugbyGoToMatchBtn.setText("Go To Match");
        RugbyGoToMatchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RugbyGoToMatchBtnActionPerformed(evt);
            }
        });

        RugbyMatchLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RugbyMatchLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RugbyMatchLbl.setText("Match:");

        javax.swing.GroupLayout RugbyPaneLayout = new javax.swing.GroupLayout(RugbyPane);
        RugbyPane.setLayout(RugbyPaneLayout);
        RugbyPaneLayout.setHorizontalGroup(
            RugbyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RugbyPaneLayout.createSequentialGroup()
                .addGroup(RugbyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RugbyPaneLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addGroup(RugbyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RugbyGoToMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RugbyPaneLayout.createSequentialGroup()
                                .addComponent(RugbyMatchLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RugbyMatchCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(RugbyPaneLayout.createSequentialGroup()
                        .addGap(498, 498, 498)
                        .addComponent(RugbyHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        RugbyPaneLayout.setVerticalGroup(
            RugbyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RugbyPaneLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(RugbyHeaderLbl)
                .addGap(76, 76, 76)
                .addGroup(RugbyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RugbyMatchCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RugbyMatchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109)
                .addComponent(RugbyGoToMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );

        SportTabbedPane.addTab("Rugby", RugbyPane);

        SoccerPane.setBackground(new java.awt.Color(51, 51, 51));
        SoccerPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        SoccerPane.setOpaque(false);

        SoccerHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        SoccerHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SoccerHeaderLbl.setText("Soccer");

        SoccerMatchCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        SoccerGoToMatchBtn.setBackground(new java.awt.Color(51, 51, 51));
        SoccerGoToMatchBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        SoccerGoToMatchBtn.setText("Go To Match");
        SoccerGoToMatchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoccerGoToMatchBtnActionPerformed(evt);
            }
        });

        SoccerMatchLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        SoccerMatchLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SoccerMatchLbl.setText("Match:");

        javax.swing.GroupLayout SoccerPaneLayout = new javax.swing.GroupLayout(SoccerPane);
        SoccerPane.setLayout(SoccerPaneLayout);
        SoccerPaneLayout.setHorizontalGroup(
            SoccerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SoccerPaneLayout.createSequentialGroup()
                .addGroup(SoccerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SoccerPaneLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addGroup(SoccerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SoccerGoToMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SoccerPaneLayout.createSequentialGroup()
                                .addComponent(SoccerMatchLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SoccerMatchCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(SoccerPaneLayout.createSequentialGroup()
                        .addGap(498, 498, 498)
                        .addComponent(SoccerHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        SoccerPaneLayout.setVerticalGroup(
            SoccerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SoccerPaneLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(SoccerHeaderLbl)
                .addGap(76, 76, 76)
                .addGroup(SoccerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoccerMatchCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoccerMatchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109)
                .addComponent(SoccerGoToMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );

        SportTabbedPane.addTab("Soccer", SoccerPane);

        AmericanFootballPane.setBackground(new java.awt.Color(51, 51, 51));
        AmericanFootballPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        AmericanFootballPane.setOpaque(false);

        AmericanFootballHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        AmericanFootballHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AmericanFootballHeaderLbl.setText("American Football");

        AmericanFootballMatchCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        AmericanFootballGoToMatchBtn.setBackground(new java.awt.Color(51, 51, 51));
        AmericanFootballGoToMatchBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        AmericanFootballGoToMatchBtn.setText("Go To Match");
        AmericanFootballGoToMatchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmericanFootballGoToMatchBtnActionPerformed(evt);
            }
        });

        AmericanFootballMatchLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        AmericanFootballMatchLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AmericanFootballMatchLbl.setText("Match:");

        javax.swing.GroupLayout AmericanFootballPaneLayout = new javax.swing.GroupLayout(AmericanFootballPane);
        AmericanFootballPane.setLayout(AmericanFootballPaneLayout);
        AmericanFootballPaneLayout.setHorizontalGroup(
            AmericanFootballPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AmericanFootballPaneLayout.createSequentialGroup()
                .addGroup(AmericanFootballPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AmericanFootballPaneLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addGroup(AmericanFootballPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AmericanFootballGoToMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AmericanFootballPaneLayout.createSequentialGroup()
                                .addComponent(AmericanFootballMatchLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AmericanFootballMatchCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AmericanFootballPaneLayout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(AmericanFootballHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        AmericanFootballPaneLayout.setVerticalGroup(
            AmericanFootballPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AmericanFootballPaneLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(AmericanFootballHeaderLbl)
                .addGap(76, 76, 76)
                .addGroup(AmericanFootballPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmericanFootballMatchCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmericanFootballMatchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109)
                .addComponent(AmericanFootballGoToMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );

        SportTabbedPane.addTab("American Football", AmericanFootballPane);

        BasketballPane.setBackground(new java.awt.Color(51, 51, 51));
        BasketballPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        BasketballPane.setOpaque(false);

        BasketballHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        BasketballHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BasketballHeaderLbl.setText("Basketball");

        BasketballMatchCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        BasketballGoToMatchBtn.setBackground(new java.awt.Color(51, 51, 51));
        BasketballGoToMatchBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BasketballGoToMatchBtn.setText("Go To Match");
        BasketballGoToMatchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasketballGoToMatchBtnActionPerformed(evt);
            }
        });

        BasketballMatchLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BasketballMatchLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BasketballMatchLbl.setText("Match:");

        javax.swing.GroupLayout BasketballPaneLayout = new javax.swing.GroupLayout(BasketballPane);
        BasketballPane.setLayout(BasketballPaneLayout);
        BasketballPaneLayout.setHorizontalGroup(
            BasketballPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasketballPaneLayout.createSequentialGroup()
                .addGroup(BasketballPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BasketballPaneLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addGroup(BasketballPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BasketballGoToMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BasketballPaneLayout.createSequentialGroup()
                                .addComponent(BasketballMatchLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BasketballMatchCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(BasketballPaneLayout.createSequentialGroup()
                        .addGap(468, 468, 468)
                        .addComponent(BasketballHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        BasketballPaneLayout.setVerticalGroup(
            BasketballPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasketballPaneLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(BasketballHeaderLbl)
                .addGap(76, 76, 76)
                .addGroup(BasketballPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BasketballMatchCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BasketballMatchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109)
                .addComponent(BasketballGoToMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );

        SportTabbedPane.addTab("Basketball", BasketballPane);

        CSGOPane.setBackground(new java.awt.Color(51, 51, 51));
        CSGOPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        CSGOPane.setOpaque(false);

        CSGOHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        CSGOHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CSGOHeaderLbl.setText("Counter-Strike: Global Offensive");

        CSGOMatchCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        CSGOGoToMatchBtn.setBackground(new java.awt.Color(51, 51, 51));
        CSGOGoToMatchBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        CSGOGoToMatchBtn.setText("Go To Match");
        CSGOGoToMatchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSGOGoToMatchBtnActionPerformed(evt);
            }
        });

        CSGOMatchLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        CSGOMatchLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CSGOMatchLbl.setText("Match:");

        javax.swing.GroupLayout CSGOPaneLayout = new javax.swing.GroupLayout(CSGOPane);
        CSGOPane.setLayout(CSGOPaneLayout);
        CSGOPaneLayout.setHorizontalGroup(
            CSGOPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CSGOPaneLayout.createSequentialGroup()
                .addGroup(CSGOPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CSGOPaneLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addGroup(CSGOPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CSGOGoToMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CSGOPaneLayout.createSequentialGroup()
                                .addComponent(CSGOMatchLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CSGOMatchCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CSGOPaneLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(CSGOHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        CSGOPaneLayout.setVerticalGroup(
            CSGOPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CSGOPaneLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(CSGOHeaderLbl)
                .addGap(76, 76, 76)
                .addGroup(CSGOPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CSGOMatchCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CSGOMatchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109)
                .addComponent(CSGOGoToMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );

        SportTabbedPane.addTab("CSGO", CSGOPane);

        LoLPane.setBackground(new java.awt.Color(51, 51, 51));
        LoLPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        LoLPane.setOpaque(false);

        LoLHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        LoLHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoLHeaderLbl.setText("Leauge of Legends");

        LoLMatchCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        LoLGoToMatchBtn.setBackground(new java.awt.Color(51, 51, 51));
        LoLGoToMatchBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        LoLGoToMatchBtn.setText("Go To Match");
        LoLGoToMatchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoLGoToMatchBtnActionPerformed(evt);
            }
        });

        LoLMatchLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        LoLMatchLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LoLMatchLbl.setText("Match:");

        javax.swing.GroupLayout LoLPaneLayout = new javax.swing.GroupLayout(LoLPane);
        LoLPane.setLayout(LoLPaneLayout);
        LoLPaneLayout.setHorizontalGroup(
            LoLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoLPaneLayout.createSequentialGroup()
                .addGroup(LoLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoLPaneLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addGroup(LoLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LoLGoToMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LoLPaneLayout.createSequentialGroup()
                                .addComponent(LoLMatchLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LoLMatchCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(LoLPaneLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(LoLHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        LoLPaneLayout.setVerticalGroup(
            LoLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoLPaneLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(LoLHeaderLbl)
                .addGap(76, 76, 76)
                .addGroup(LoLPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoLMatchCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoLMatchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109)
                .addComponent(LoLGoToMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );

        SportTabbedPane.addTab("LoL", LoLPane);

        Dota2Pane.setBackground(new java.awt.Color(51, 51, 51));
        Dota2Pane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Dota2Pane.setOpaque(false);

        Dota2HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        Dota2HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dota2HeaderLbl.setText("Dota 2");

        Dota2MatchCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        Dota2GoToMatchBtn.setBackground(new java.awt.Color(51, 51, 51));
        Dota2GoToMatchBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Dota2GoToMatchBtn.setText("Go To Match");
        Dota2GoToMatchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dota2GoToMatchBtnActionPerformed(evt);
            }
        });

        Dota2MatchLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Dota2MatchLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Dota2MatchLbl.setText("Match:");

        javax.swing.GroupLayout Dota2PaneLayout = new javax.swing.GroupLayout(Dota2Pane);
        Dota2Pane.setLayout(Dota2PaneLayout);
        Dota2PaneLayout.setHorizontalGroup(
            Dota2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dota2PaneLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addGroup(Dota2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dota2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Dota2GoToMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Dota2PaneLayout.createSequentialGroup()
                            .addComponent(Dota2MatchLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Dota2MatchCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Dota2HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        Dota2PaneLayout.setVerticalGroup(
            Dota2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dota2PaneLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Dota2HeaderLbl)
                .addGap(76, 76, 76)
                .addGroup(Dota2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dota2MatchCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dota2MatchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109)
                .addComponent(Dota2GoToMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );

        SportTabbedPane.addTab("Dota 2", Dota2Pane);

        AccuPicksHeaderLbl.setBackground(new java.awt.Color(0, 0, 0));
        AccuPicksHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 60)); // NOI18N
        AccuPicksHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        AccuPicksHeaderLbl.setText("AccuPicks");

        LiveScoreKeepingLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        LiveScoreKeepingLbl.setText("Live Score Keeping");

        AccountNameLbl.setText("AccountName");

        BackBtn.setBackground(new java.awt.Color(51, 51, 51));
        BackBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(574, 574, 574)
                                .addComponent(LiveScoreKeepingLbl))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(486, 486, 486)
                                .addComponent(AccuPicksHeaderLbl))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(615, 615, 615)
                                .addComponent(AccountNameLbl)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SportTabbedPane)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(AccuPicksHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LiveScoreKeepingLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AccountNameLbl)
                .addGap(18, 18, 18)
                .addComponent(SportTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CricketGoToMatchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CricketGoToMatchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CricketGoToMatchBtnActionPerformed

    private void RugbyGoToMatchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RugbyGoToMatchBtnActionPerformed
        new RugbyLiveScoreKeepingGameData(CLIENT).setVisible(true);
        dispose();
    }//GEN-LAST:event_RugbyGoToMatchBtnActionPerformed

    private void SoccerGoToMatchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoccerGoToMatchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoccerGoToMatchBtnActionPerformed

    private void AmericanFootballGoToMatchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmericanFootballGoToMatchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmericanFootballGoToMatchBtnActionPerformed

    private void BasketballGoToMatchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasketballGoToMatchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BasketballGoToMatchBtnActionPerformed

    private void CSGOGoToMatchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSGOGoToMatchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CSGOGoToMatchBtnActionPerformed

    private void LoLGoToMatchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoLGoToMatchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoLGoToMatchBtnActionPerformed

    private void Dota2GoToMatchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dota2GoToMatchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dota2GoToMatchBtnActionPerformed

    private void SportTabbedPaneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SportTabbedPaneKeyPressed
        //String Sport = jTabbedPane1
    }//GEN-LAST:event_SportTabbedPaneKeyPressed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        new AdminHome(CLIENT).setVisible(true);
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiveScoreKeepingHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiveScoreKeepingHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiveScoreKeepingHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiveScoreKeepingHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LiveScoreKeepingHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNameLbl;
    private javax.swing.JLabel AccuPicksHeaderLbl;
    private javax.swing.JButton AmericanFootballGoToMatchBtn;
    private javax.swing.JLabel AmericanFootballHeaderLbl;
    private javax.swing.JComboBox AmericanFootballMatchCmb;
    private javax.swing.JLabel AmericanFootballMatchLbl;
    private javax.swing.JPanel AmericanFootballPane;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton BasketballGoToMatchBtn;
    private javax.swing.JLabel BasketballHeaderLbl;
    private javax.swing.JComboBox BasketballMatchCmb;
    private javax.swing.JLabel BasketballMatchLbl;
    private javax.swing.JPanel BasketballPane;
    private javax.swing.JButton CSGOGoToMatchBtn;
    private javax.swing.JLabel CSGOHeaderLbl;
    private javax.swing.JComboBox CSGOMatchCmb;
    private javax.swing.JLabel CSGOMatchLbl;
    private javax.swing.JPanel CSGOPane;
    private javax.swing.JButton CricketGoToMatchBtn;
    private javax.swing.JLabel CricketHeaderLbl;
    private javax.swing.JComboBox CricketMatchCmb;
    private javax.swing.JLabel CricketMatchLbl;
    private javax.swing.JPanel CricketPane;
    private javax.swing.JButton Dota2GoToMatchBtn;
    private javax.swing.JLabel Dota2HeaderLbl;
    private javax.swing.JComboBox Dota2MatchCmb;
    private javax.swing.JLabel Dota2MatchLbl;
    private javax.swing.JPanel Dota2Pane;
    private javax.swing.JLabel LiveScoreKeepingLbl;
    private javax.swing.JButton LoLGoToMatchBtn;
    private javax.swing.JLabel LoLHeaderLbl;
    private javax.swing.JComboBox LoLMatchCmb;
    private javax.swing.JLabel LoLMatchLbl;
    private javax.swing.JPanel LoLPane;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton RugbyGoToMatchBtn;
    private javax.swing.JLabel RugbyHeaderLbl;
    private javax.swing.JComboBox RugbyMatchCmb;
    private javax.swing.JLabel RugbyMatchLbl;
    private javax.swing.JPanel RugbyPane;
    private javax.swing.JButton SoccerGoToMatchBtn;
    private javax.swing.JLabel SoccerHeaderLbl;
    private javax.swing.JComboBox SoccerMatchCmb;
    private javax.swing.JLabel SoccerMatchLbl;
    private javax.swing.JPanel SoccerPane;
    private javax.swing.JTabbedPane SportTabbedPane;
    // End of variables declaration//GEN-END:variables
}
