/*
 * Sport score preditcion software
 * by Ronnie Muller & Stephan Malan
 */
package com.accupicks.client;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Ronnie
 */
public class LogInRegister extends javax.swing.JFrame {
JLabel backgroundLbl = new JLabel();
    /**
     * Creates new form LogInRegister
     */
    public LogInRegister() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        setLayout(new BorderLayout());
        add(backgroundLbl);
        backgroundLbl.setIcon(new ImageIcon(new ImageIcon(AdminHome.class.getResource("/resources/HomeBackground1.jpg")).getImage().getScaledInstance(1366, 768, java.awt.Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        NameHeaderLbl = new javax.swing.JLabel();
        NameTxf = new javax.swing.JTextField();
        SecurityAnswerTxf = new javax.swing.JTextField();
        SecurityQuestionHeaderLbl = new javax.swing.JLabel();
        UsernameTxf = new javax.swing.JTextField();
        AccuPicksHeaderLbl = new javax.swing.JLabel();
        UsernameHeaderLbl = new javax.swing.JLabel();
        SecurityAnswerHeaderLbl = new javax.swing.JLabel();
        RegisterHeaderLbl = new javax.swing.JLabel();
        ConfirmPasswordHeaderLbl = new javax.swing.JLabel();
        PasswordHeaderLbl = new javax.swing.JLabel();
        SecurityQuestionTxf = new javax.swing.JComboBox();
        RegisterBtn = new javax.swing.JButton();
        AvailableLbl = new javax.swing.JLabel();
        PasswordTxf = new javax.swing.JPasswordField();
        CPasswordTxf = new javax.swing.JPasswordField();
        BackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        NameHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        NameHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NameHeaderLbl.setText("Name:");

        NameTxf.setBackground(new java.awt.Color(51, 51, 51));
        NameTxf.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        NameTxf.setForeground(new java.awt.Color(255, 255, 255));

        SecurityAnswerTxf.setBackground(new java.awt.Color(51, 51, 51));
        SecurityAnswerTxf.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        SecurityAnswerTxf.setForeground(new java.awt.Color(255, 255, 255));

        SecurityQuestionHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        SecurityQuestionHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SecurityQuestionHeaderLbl.setText("Securtiy Question:");

        UsernameTxf.setBackground(new java.awt.Color(51, 51, 51));
        UsernameTxf.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        UsernameTxf.setForeground(new java.awt.Color(255, 255, 255));
        UsernameTxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTxfActionPerformed(evt);
            }
        });

        AccuPicksHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 60)); // NOI18N
        AccuPicksHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        AccuPicksHeaderLbl.setText("AccuPicks");

        UsernameHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        UsernameHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UsernameHeaderLbl.setText("UserName:");

        SecurityAnswerHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        SecurityAnswerHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SecurityAnswerHeaderLbl.setText("Securtiy Answer:");

        RegisterHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        RegisterHeaderLbl.setText("Register");

        ConfirmPasswordHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        ConfirmPasswordHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ConfirmPasswordHeaderLbl.setText("Confirm Password:");

        PasswordHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        PasswordHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PasswordHeaderLbl.setText("Password:");

        SecurityQuestionTxf.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        RegisterBtn.setBackground(new java.awt.Color(51, 51, 51));
        RegisterBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegisterBtn.setText("Register");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });

        AvailableLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        AvailableLbl.setText("Not Available");

        PasswordTxf.setBackground(new java.awt.Color(51, 51, 51));
        PasswordTxf.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        PasswordTxf.setForeground(new java.awt.Color(255, 255, 255));

        CPasswordTxf.setBackground(new java.awt.Color(51, 51, 51));
        CPasswordTxf.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        CPasswordTxf.setForeground(new java.awt.Color(255, 255, 255));

        BackBtn.setBackground(new java.awt.Color(51, 51, 51));
        BackBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(AccuPicksHeaderLbl))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(598, 598, 598)
                        .addComponent(RegisterHeaderLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NameHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UsernameHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PasswordHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ConfirmPasswordHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CPasswordTxf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordTxf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernameTxf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameTxf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SecurityAnswerHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SecurityQuestionHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SecurityAnswerTxf)
                                .addComponent(SecurityQuestionTxf, 0, 350, Short.MAX_VALUE)))))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AvailableLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(AccuPicksHeaderLbl)
                .addGap(18, 18, 18)
                .addComponent(RegisterHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AvailableLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPasswordTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmPasswordHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecurityQuestionTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecurityQuestionHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecurityAnswerHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecurityAnswerTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTxfActionPerformed
/*
        try {

            BufferedReader bf = new BufferedReader(new FileReader("C:\\Program Files\\AccuPicks\\Login\\UserLogins.txt"));
            String AdminUser = bf.readLine();
            do{
                String UserName = AdminUser.substring(0,AdminUser.indexOf(";"));
                if (UserName.matches(UsernameTxf.getText())){
                    AvailableLbl.setText("Not Available");
                }else{
                    AvailableLbl.setText("Available");
                }
                AdminUser = bf.readLine();
            }while(AdminUser!=null);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_UsernameTxfActionPerformed

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
/*
        if(PasswordTxf.getText().matches(CPasswordTxf.getText())){
            String Password = null;
            Password = PasswordTxf.getText();
            String Name = NameTxf.getText();
            String Username = UsernameTxf.getText();
            String SecurityQ = (String) SecurityQTxf.getSelectedItem();
            String SecurityA = SecurityATxf.getText();
            String line;
            String UID = null;

            int op = JOptionPane.showConfirmDialog(null, "Are you sure the following information is correct?\nName: " + Name + "\nUsername: " + Username + "Password: " + PasswordTxf.getText() + "\nSecurity Question: " + SecurityQ + "\nSecurity Answer: " + SecurityA + "\n\n\n");

            if(op==0){

                try {
                    Scanner s = new Scanner(new File("C:\\\\Program Files\\\\AccuPicks\\\\Login\\\\UserLogins.txt"));

                    while (s.hasNextLine()) {
                        line = s.nextLine();
                        UID = line.substring(0,line.indexOf(";"));
                    }

                } catch (FileNotFoundException ex) {
                    Logger.getLogger(LoginRegister.class.getName()).log(Level.SEVERE, null, ex);
                }

                try {
                    Scanner sc = new Scanner(new File("C:\\\\Program Files\\\\AccuPicks\\\\Login\\\\UserLogins.txt"));
                    ArrayList<String> lines = new ArrayList<String>();

                    while (sc.hasNextLine()) {
                        lines.add(sc.nextLine());
                    }

                    FileWriter Writer = new FileWriter(new File("C:\\Program Files\\AccuPicks\\Login\\UserLogins.txt"));

                    for (int i = 0; i < lines.size(); i++) {
                        Writer.append(lines.get(i));
                        Writer.append(System.lineSeparator());
                    }

                    Writer.write(Integer.toString(Integer.parseInt(UID)+1) + ";" + Username + ";" + Password + ";" + Name + ";" + "User;" + SecurityQ + ";" + SecurityA);
                    Writer.close();

                }catch(FileNotFoundException ex){
                    System.out.println("File Not Found");
                }catch(IOException ex){
                    System.out.println("IO");
                }
            }
        }else{
            System.out.println("Passwords do not match.");
        }
*/
    }//GEN-LAST:event_RegisterBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        //new LogIn().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccuPicksHeaderLbl;
    private javax.swing.JLabel AvailableLbl;
    private javax.swing.JButton BackBtn;
    private javax.swing.JPasswordField CPasswordTxf;
    private javax.swing.JLabel ConfirmPasswordHeaderLbl;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel NameHeaderLbl;
    private javax.swing.JTextField NameTxf;
    private javax.swing.JLabel PasswordHeaderLbl;
    private javax.swing.JPasswordField PasswordTxf;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JLabel RegisterHeaderLbl;
    private javax.swing.JLabel SecurityAnswerHeaderLbl;
    private javax.swing.JTextField SecurityAnswerTxf;
    private javax.swing.JLabel SecurityQuestionHeaderLbl;
    private javax.swing.JComboBox SecurityQuestionTxf;
    private javax.swing.JLabel UsernameHeaderLbl;
    private javax.swing.JTextField UsernameTxf;
    // End of variables declaration//GEN-END:variables
}
