/*
 * Sport score preditcion software
 * by Ronnie Muller & Stephan Malan
 */
package com.accupicks.client;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import com.shared.Client;

/**
 *
 * @author Ronnie
 */
public class RegRemTeamPlayer extends javax.swing.JFrame {
JLabel backgroundLbl = new JLabel();
private final Client CLIENT;
    /**
     * Creates new form RegRemTeamPlayer
     */
    public RegRemTeamPlayer(Client client) {
        CLIENT = client;
        initComponents();
        setLocationRelativeTo(null);
        AccountNameLbl.setText(CLIENT.getName());
        
        setLayout(new BorderLayout());
        add(backgroundLbl);
        backgroundLbl.setIcon(new ImageIcon(new ImageIcon(AdminHome.class.getResource("/resources/HomeBackground1.jpg")).getImage().getScaledInstance(1366, 768, java.awt.Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        RegRemTabbedPanel = new javax.swing.JTabbedPane();
        RegPlayTeamTourTabbedPane = new javax.swing.JTabbedPane();
        RegTourPanel = new javax.swing.JPanel();
        RegTourRegisterHeaderLbl = new javax.swing.JLabel();
        RegTourTournamentMainHeaderLbl = new javax.swing.JLabel();
        RegTourBtn = new javax.swing.JButton();
        RegTourTournamentHeaderLbl = new javax.swing.JLabel();
        jComboBox22 = new javax.swing.JComboBox();
        RegTourSportHeaderLbl = new javax.swing.JLabel();
        AccountNametxf2 = new javax.swing.JTextField();
        RegPlayPanel = new javax.swing.JPanel();
        RegPlayRegisterHeaderLbl = new javax.swing.JLabel();
        RegPlayPlayerHeaderLbl = new javax.swing.JLabel();
        RegPlayTournamentCmb = new javax.swing.JComboBox();
        RegPlayBtn = new javax.swing.JButton();
        RegPlayTournamentHeaderLbl = new javax.swing.JLabel();
        RegPlaySportCmb = new javax.swing.JComboBox();
        RegPlaySportHeaderLbl = new javax.swing.JLabel();
        RegPlayTeamHeaderLbl = new javax.swing.JLabel();
        RegPlayNameHeaderLbl = new javax.swing.JLabel();
        RegPlayNameTxf = new javax.swing.JTextField();
        RegPlaySurnameTxf = new javax.swing.JTextField();
        RegPlaySurnameHeaderLbl = new javax.swing.JLabel();
        RegPlayTeamCmb = new javax.swing.JComboBox();
        RegTeamPanel = new javax.swing.JPanel();
        RegTeamRegisterHeaderLbl = new javax.swing.JLabel();
        RegTeamTeamHeaderLbl = new javax.swing.JLabel();
        RegTeamBtn = new javax.swing.JButton();
        RegTeamTournamentHeaderLbl = new javax.swing.JLabel();
        RegTeamSportCmb = new javax.swing.JComboBox();
        RegTeamSportHeaderLbl = new javax.swing.JLabel();
        RegTeamTeamnameTxf = new javax.swing.JTextField();
        RegTeamTeamnameHeaderLbl = new javax.swing.JLabel();
        RegTeamTournamentCmb = new javax.swing.JComboBox();
        RemPlayTeamTourTabbedPane = new javax.swing.JTabbedPane();
        RemTourPanel = new javax.swing.JPanel();
        RemTourRemoveHeaderLbl = new javax.swing.JLabel();
        RemTourTournamentMainHeaderLbl = new javax.swing.JLabel();
        RemTourTournamentCmb = new javax.swing.JComboBox();
        RemTourBtn = new javax.swing.JButton();
        RemTourTournamentHeaderLbl = new javax.swing.JLabel();
        RemTourSportCmb = new javax.swing.JComboBox();
        RemTourSportHeaderLbl = new javax.swing.JLabel();
        RemPlayPanel = new javax.swing.JPanel();
        RemPlayRemoveHeaderLbl = new javax.swing.JLabel();
        RemPlayPlayerHeaderLbl = new javax.swing.JLabel();
        RemPlayTournamentCmb = new javax.swing.JComboBox();
        RemPlayBtn = new javax.swing.JButton();
        RemPlayTournamentHeaderLbl = new javax.swing.JLabel();
        RemPlaySportCmb = new javax.swing.JComboBox();
        RemPlaySportHeaderLbl = new javax.swing.JLabel();
        RemPlayTeamHeaderLbl = new javax.swing.JLabel();
        RemPlayTeamCmb = new javax.swing.JComboBox();
        RemPlayNameCmb = new javax.swing.JComboBox();
        RemPlayNameHeaderLbl = new javax.swing.JLabel();
        RemTeamPanel = new javax.swing.JPanel();
        RemTeamRemoveHeaderLbl = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        RugbyGoToMatchBtn4 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jComboBox16 = new javax.swing.JComboBox();
        jLabel50 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jComboBox19 = new javax.swing.JComboBox();
        jComboBox20 = new javax.swing.JComboBox();
        AccuPicksHeaderLbl = new javax.swing.JLabel();
        AccountNameLbl = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        MainPanel.setOpaque(false);

        RegPlayTeamTourTabbedPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        RegTourPanel.setBackground(new java.awt.Color(51, 51, 51));
        RegTourPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        RegTourPanel.setOpaque(false);

        RegTourRegisterHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        RegTourRegisterHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegTourRegisterHeaderLbl.setText("Register");

        RegTourTournamentMainHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        RegTourTournamentMainHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegTourTournamentMainHeaderLbl.setText("Tournament");

        RegTourBtn.setBackground(new java.awt.Color(51, 51, 51));
        RegTourBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegTourBtn.setText("Register Tournament");

        RegTourTournamentHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegTourTournamentHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RegTourTournamentHeaderLbl.setText("tournament:");

        jComboBox22.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jComboBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox22ActionPerformed(evt);
            }
        });

        RegTourSportHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegTourSportHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RegTourSportHeaderLbl.setText("Sport:");

        AccountNametxf2.setBackground(new java.awt.Color(51, 51, 51));
        AccountNametxf2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        AccountNametxf2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout RegTourPanelLayout = new javax.swing.GroupLayout(RegTourPanel);
        RegTourPanel.setLayout(RegTourPanelLayout);
        RegTourPanelLayout.setHorizontalGroup(
            RegTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegTourPanelLayout.createSequentialGroup()
                .addGroup(RegTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegTourPanelLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(RegTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegTourTournamentHeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegTourSportHeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox22, 0, 303, Short.MAX_VALUE)
                                .addComponent(RegTourRegisterHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(AccountNametxf2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RegTourPanelLayout.createSequentialGroup()
                        .addGap(580, 580, 580)
                        .addComponent(RegTourTournamentMainHeaderLbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegTourPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RegTourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(0, 523, Short.MAX_VALUE))
        );
        RegTourPanelLayout.setVerticalGroup(
            RegTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegTourPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(RegTourRegisterHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegTourTournamentMainHeaderLbl)
                .addGap(18, 18, 18)
                .addGroup(RegTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegTourSportHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegTourTournamentHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountNametxf2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RegTourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        RegPlayTeamTourTabbedPane.addTab("Tournament", RegTourPanel);

        RegPlayPanel.setBackground(new java.awt.Color(51, 51, 51));
        RegPlayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        RegPlayPanel.setOpaque(false);

        RegPlayRegisterHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        RegPlayRegisterHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegPlayRegisterHeaderLbl.setText("Register");

        RegPlayPlayerHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        RegPlayPlayerHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegPlayPlayerHeaderLbl.setText("Player");

        RegPlayTournamentCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        RegPlayBtn.setBackground(new java.awt.Color(51, 51, 51));
        RegPlayBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegPlayBtn.setText("Register Player");

        RegPlayTournamentHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegPlayTournamentHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RegPlayTournamentHeaderLbl.setText("tournament:");

        RegPlaySportCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegPlaySportCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegPlaySportCmbActionPerformed(evt);
            }
        });

        RegPlaySportHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegPlaySportHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RegPlaySportHeaderLbl.setText("Sport:");

        RegPlayTeamHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegPlayTeamHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RegPlayTeamHeaderLbl.setText("Team:");

        RegPlayNameHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegPlayNameHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RegPlayNameHeaderLbl.setText("Name:");

        RegPlayNameTxf.setBackground(new java.awt.Color(51, 51, 51));
        RegPlayNameTxf.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegPlayNameTxf.setForeground(new java.awt.Color(255, 255, 255));

        RegPlaySurnameTxf.setBackground(new java.awt.Color(51, 51, 51));
        RegPlaySurnameTxf.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegPlaySurnameTxf.setForeground(new java.awt.Color(255, 255, 255));

        RegPlaySurnameHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegPlaySurnameHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RegPlaySurnameHeaderLbl.setText("Surname:");

        RegPlayTeamCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegPlayTeamCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegPlayTeamCmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegPlayPanelLayout = new javax.swing.GroupLayout(RegPlayPanel);
        RegPlayPanel.setLayout(RegPlayPanelLayout);
        RegPlayPanelLayout.setHorizontalGroup(
            RegPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegPlayPanelLayout.createSequentialGroup()
                .addGroup(RegPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegPlayPanelLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(RegPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegPlayPanelLayout.createSequentialGroup()
                                .addGroup(RegPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RegPlayTournamentHeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(RegPlaySportHeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(RegPlayTeamHeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(RegPlayNameHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(RegPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(RegPlayTeamCmb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RegPlaySportCmb, javax.swing.GroupLayout.Alignment.LEADING, 0, 314, Short.MAX_VALUE)
                                    .addComponent(RegPlayRegisterHeaderLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RegPlayTournamentCmb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RegPlayNameTxf)))
                            .addGroup(RegPlayPanelLayout.createSequentialGroup()
                                .addComponent(RegPlaySurnameHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(RegPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegPlayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RegPlaySurnameTxf))))
                        .addGap(403, 403, 403))
                    .addGroup(RegPlayPanelLayout.createSequentialGroup()
                        .addGap(587, 587, 587)
                        .addComponent(RegPlayPlayerHeaderLbl)))
                .addGap(126, 126, 126))
        );
        RegPlayPanelLayout.setVerticalGroup(
            RegPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegPlayPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(RegPlayRegisterHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegPlayPlayerHeaderLbl)
                .addGap(18, 18, 18)
                .addGroup(RegPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegPlaySportCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegPlaySportHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegPlayTournamentHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegPlayTournamentCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegPlayTeamHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegPlayTeamCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegPlayNameHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegPlayNameTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegPlaySurnameHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegPlaySurnameTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RegPlayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RegPlayTeamTourTabbedPane.addTab("Player", RegPlayPanel);

        RegTeamPanel.setBackground(new java.awt.Color(51, 51, 51));
        RegTeamPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        RegTeamPanel.setOpaque(false);

        RegTeamRegisterHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        RegTeamRegisterHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegTeamRegisterHeaderLbl.setText("Register");

        RegTeamTeamHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        RegTeamTeamHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegTeamTeamHeaderLbl.setText("Team");

        RegTeamBtn.setBackground(new java.awt.Color(51, 51, 51));
        RegTeamBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegTeamBtn.setText("Register Team");

        RegTeamTournamentHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegTeamTournamentHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RegTeamTournamentHeaderLbl.setText("Tournament:");

        RegTeamSportCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegTeamSportCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegTeamSportCmbActionPerformed(evt);
            }
        });

        RegTeamSportHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegTeamSportHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RegTeamSportHeaderLbl.setText("Sport:");

        RegTeamTeamnameTxf.setBackground(new java.awt.Color(51, 51, 51));
        RegTeamTeamnameTxf.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegTeamTeamnameTxf.setForeground(new java.awt.Color(255, 255, 255));

        RegTeamTeamnameHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegTeamTeamnameHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RegTeamTeamnameHeaderLbl.setText("TeamName:");

        RegTeamTournamentCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RegTeamTournamentCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegTeamTournamentCmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegTeamPanelLayout = new javax.swing.GroupLayout(RegTeamPanel);
        RegTeamPanel.setLayout(RegTeamPanelLayout);
        RegTeamPanelLayout.setHorizontalGroup(
            RegTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegTeamPanelLayout.createSequentialGroup()
                .addGroup(RegTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegTeamPanelLayout.createSequentialGroup()
                        .addGap(587, 587, 587)
                        .addComponent(RegTeamTeamHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegTeamPanelLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(RegTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegTeamPanelLayout.createSequentialGroup()
                                .addComponent(RegTeamTeamnameHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RegTeamTeamnameTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegTeamPanelLayout.createSequentialGroup()
                                .addGroup(RegTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegTeamTournamentHeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegTeamSportHeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(RegTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RegTeamSportCmb, 0, 303, Short.MAX_VALUE)
                                    .addComponent(RegTeamBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                    .addComponent(RegTeamRegisterHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RegTeamTournamentCmb, 0, 303, Short.MAX_VALUE))))))
                .addContainerGap(523, Short.MAX_VALUE))
        );
        RegTeamPanelLayout.setVerticalGroup(
            RegTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegTeamPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(RegTeamRegisterHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegTeamTeamHeaderLbl)
                .addGap(18, 18, 18)
                .addGroup(RegTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegTeamSportCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegTeamSportHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegTeamTournamentHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegTeamTournamentCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegTeamTeamnameHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegTeamTeamnameTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RegTeamBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        RegPlayTeamTourTabbedPane.addTab("Team", RegTeamPanel);

        RegRemTabbedPanel.addTab("Register", RegPlayTeamTourTabbedPane);

        RemPlayTeamTourTabbedPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        RemTourPanel.setBackground(new java.awt.Color(51, 51, 51));
        RemTourPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        RemTourPanel.setOpaque(false);

        RemTourRemoveHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        RemTourRemoveHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RemTourRemoveHeaderLbl.setText("Remove");

        RemTourTournamentMainHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        RemTourTournamentMainHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RemTourTournamentMainHeaderLbl.setText("Tournament");

        RemTourTournamentCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        RemTourBtn.setBackground(new java.awt.Color(51, 51, 51));
        RemTourBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RemTourBtn.setText("Remove Tournament");

        RemTourTournamentHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RemTourTournamentHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RemTourTournamentHeaderLbl.setText("tournament:");

        RemTourSportCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RemTourSportCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemTourSportCmbActionPerformed(evt);
            }
        });

        RemTourSportHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RemTourSportHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RemTourSportHeaderLbl.setText("Sport:");

        javax.swing.GroupLayout RemTourPanelLayout = new javax.swing.GroupLayout(RemTourPanel);
        RemTourPanel.setLayout(RemTourPanelLayout);
        RemTourPanelLayout.setHorizontalGroup(
            RemTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemTourPanelLayout.createSequentialGroup()
                .addGroup(RemTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RemTourPanelLayout.createSequentialGroup()
                        .addGap(577, 577, 577)
                        .addComponent(RemTourTournamentMainHeaderLbl))
                    .addGroup(RemTourPanelLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(RemTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RemTourTournamentHeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemTourSportHeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RemTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RemTourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RemTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(RemTourSportCmb, 0, 303, Short.MAX_VALUE)
                                .addComponent(RemTourTournamentCmb, 0, 303, Short.MAX_VALUE)
                                .addComponent(RemTourRemoveHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 523, Short.MAX_VALUE))
        );
        RemTourPanelLayout.setVerticalGroup(
            RemTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemTourPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(RemTourRemoveHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemTourTournamentMainHeaderLbl)
                .addGap(18, 18, 18)
                .addGroup(RemTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemTourSportCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemTourSportHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RemTourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RemTourTournamentHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemTourTournamentCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RemTourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        RemPlayTeamTourTabbedPane.addTab("Tournament", RemTourPanel);

        RemPlayPanel.setBackground(new java.awt.Color(51, 51, 51));
        RemPlayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        RemPlayPanel.setOpaque(false);

        RemPlayRemoveHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        RemPlayRemoveHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RemPlayRemoveHeaderLbl.setText("Remove");

        RemPlayPlayerHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        RemPlayPlayerHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RemPlayPlayerHeaderLbl.setText("Player");

        RemPlayTournamentCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        RemPlayBtn.setBackground(new java.awt.Color(51, 51, 51));
        RemPlayBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RemPlayBtn.setText("Register Player");

        RemPlayTournamentHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RemPlayTournamentHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RemPlayTournamentHeaderLbl.setText("Tournament:");

        RemPlaySportCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RemPlaySportCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemPlaySportCmbActionPerformed(evt);
            }
        });

        RemPlaySportHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RemPlaySportHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RemPlaySportHeaderLbl.setText("Sport:");

        RemPlayTeamHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RemPlayTeamHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RemPlayTeamHeaderLbl.setText("Team:");

        RemPlayTeamCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        RemPlayNameCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        RemPlayNameHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RemPlayNameHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RemPlayNameHeaderLbl.setText("Name:");

        javax.swing.GroupLayout RemPlayPanelLayout = new javax.swing.GroupLayout(RemPlayPanel);
        RemPlayPanel.setLayout(RemPlayPanelLayout);
        RemPlayPanelLayout.setHorizontalGroup(
            RemPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemPlayPanelLayout.createSequentialGroup()
                .addGroup(RemPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RemPlayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RemPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(RemPlayPanelLayout.createSequentialGroup()
                            .addGap(587, 587, 587)
                            .addComponent(RemPlayPlayerHeaderLbl))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RemPlayPanelLayout.createSequentialGroup()
                            .addGap(476, 476, 476)
                            .addComponent(RemPlayRemoveHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(RemPlayPanelLayout.createSequentialGroup()
                            .addGap(280, 280, 280)
                            .addGroup(RemPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(RemPlayPanelLayout.createSequentialGroup()
                                    .addComponent(RemPlayNameHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(RemPlayNameCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(RemPlayPanelLayout.createSequentialGroup()
                                    .addGroup(RemPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RemPlayTournamentHeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(RemPlaySportHeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(RemPlayTeamHeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(RemPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RemPlaySportCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(RemPlayTournamentCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(RemPlayTeamCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(523, Short.MAX_VALUE))
        );
        RemPlayPanelLayout.setVerticalGroup(
            RemPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemPlayPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(RemPlayRemoveHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemPlayPlayerHeaderLbl)
                .addGap(18, 18, 18)
                .addGroup(RemPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemPlaySportCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemPlaySportHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RemPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RemPlayTournamentHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemPlayTournamentCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RemPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemPlayTeamHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemPlayTeamCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RemPlayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemPlayNameHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemPlayNameCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RemPlayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        RemPlayTeamTourTabbedPane.addTab("Player", RemPlayPanel);

        RemTeamPanel.setBackground(new java.awt.Color(51, 51, 51));
        RemTeamPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        RemTeamPanel.setOpaque(false);

        RemTeamRemoveHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        RemTeamRemoveHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RemTeamRemoveHeaderLbl.setText("Remove");

        jLabel41.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Team");

        RugbyGoToMatchBtn4.setBackground(new java.awt.Color(51, 51, 51));
        RugbyGoToMatchBtn4.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RugbyGoToMatchBtn4.setText("Register Team");

        jLabel49.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel49.setText("Tournament:");

        jComboBox16.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jComboBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox16ActionPerformed(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel50.setText("Sport:");

        jLabel53.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel53.setText("TeamName:");

        jComboBox19.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jComboBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox19ActionPerformed(evt);
            }
        });

        jComboBox20.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jComboBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RemTeamPanelLayout = new javax.swing.GroupLayout(RemTeamPanel);
        RemTeamPanel.setLayout(RemTeamPanelLayout);
        RemTeamPanelLayout.setHorizontalGroup(
            RemTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemTeamPanelLayout.createSequentialGroup()
                .addGroup(RemTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RemTeamPanelLayout.createSequentialGroup()
                        .addGap(587, 587, 587)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RemTeamPanelLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(RemTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RemTeamPanelLayout.createSequentialGroup()
                                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox20, 0, 324, Short.MAX_VALUE))
                            .addGroup(RemTeamPanelLayout.createSequentialGroup()
                                .addGroup(RemTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(RemTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox16, 0, 303, Short.MAX_VALUE)
                                    .addComponent(RugbyGoToMatchBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                    .addComponent(jComboBox19, 0, 303, Short.MAX_VALUE)
                                    .addComponent(RemTeamRemoveHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(502, Short.MAX_VALUE))
        );
        RemTeamPanelLayout.setVerticalGroup(
            RemTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemTeamPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(RemTeamRemoveHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addGap(18, 18, 18)
                .addGroup(RemTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RemTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RemTeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(RugbyGoToMatchBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        RemPlayTeamTourTabbedPane.addTab("Team", RemTeamPanel);

        RegRemTabbedPanel.addTab("Remove", RemPlayTeamTourTabbedPane);

        AccuPicksHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 60)); // NOI18N
        AccuPicksHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        AccuPicksHeaderLbl.setText("AccuPicks");

        AccountNameLbl.setText("AccountName");

        BackBtn.setBackground(new java.awt.Color(51, 51, 51));
        BackBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(623, 623, 623)
                                .addComponent(AccountNameLbl))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(490, 490, 490)
                                .addComponent(AccuPicksHeaderLbl)))
                        .addGap(0, 506, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RegRemTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AccuPicksHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(AccountNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegRemTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemPlaySportCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemPlaySportCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemPlaySportCmbActionPerformed

    private void jComboBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox16ActionPerformed

    private void jComboBox19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox19ActionPerformed

    private void jComboBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox20ActionPerformed

    private void RemTourSportCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemTourSportCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemTourSportCmbActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        new AdminHome(CLIENT).setVisible(true);
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void jComboBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox22ActionPerformed

    private void RegTeamTournamentCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegTeamTournamentCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegTeamTournamentCmbActionPerformed

    private void RegTeamSportCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegTeamSportCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegTeamSportCmbActionPerformed

    private void RegPlaySportCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegPlaySportCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegPlaySportCmbActionPerformed

    private void RegPlayTeamCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegPlayTeamCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegPlayTeamCmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegRemTeamPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegRemTeamPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegRemTeamPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegRemTeamPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RegRemTeamPlayer(CLIENT).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNameLbl;
    private javax.swing.JTextField AccountNametxf2;
    private javax.swing.JLabel AccuPicksHeaderLbl;
    private javax.swing.JButton BackBtn;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton RegPlayBtn;
    private javax.swing.JLabel RegPlayNameHeaderLbl;
    private javax.swing.JTextField RegPlayNameTxf;
    private javax.swing.JPanel RegPlayPanel;
    private javax.swing.JLabel RegPlayPlayerHeaderLbl;
    private javax.swing.JLabel RegPlayRegisterHeaderLbl;
    private javax.swing.JComboBox RegPlaySportCmb;
    private javax.swing.JLabel RegPlaySportHeaderLbl;
    private javax.swing.JLabel RegPlaySurnameHeaderLbl;
    private javax.swing.JTextField RegPlaySurnameTxf;
    private javax.swing.JComboBox RegPlayTeamCmb;
    private javax.swing.JLabel RegPlayTeamHeaderLbl;
    private javax.swing.JTabbedPane RegPlayTeamTourTabbedPane;
    private javax.swing.JComboBox RegPlayTournamentCmb;
    private javax.swing.JLabel RegPlayTournamentHeaderLbl;
    private javax.swing.JTabbedPane RegRemTabbedPanel;
    private javax.swing.JButton RegTeamBtn;
    private javax.swing.JPanel RegTeamPanel;
    private javax.swing.JLabel RegTeamRegisterHeaderLbl;
    private javax.swing.JComboBox RegTeamSportCmb;
    private javax.swing.JLabel RegTeamSportHeaderLbl;
    private javax.swing.JLabel RegTeamTeamHeaderLbl;
    private javax.swing.JLabel RegTeamTeamnameHeaderLbl;
    private javax.swing.JTextField RegTeamTeamnameTxf;
    private javax.swing.JComboBox RegTeamTournamentCmb;
    private javax.swing.JLabel RegTeamTournamentHeaderLbl;
    private javax.swing.JButton RegTourBtn;
    private javax.swing.JPanel RegTourPanel;
    private javax.swing.JLabel RegTourRegisterHeaderLbl;
    private javax.swing.JLabel RegTourSportHeaderLbl;
    private javax.swing.JLabel RegTourTournamentHeaderLbl;
    private javax.swing.JLabel RegTourTournamentMainHeaderLbl;
    private javax.swing.JButton RemPlayBtn;
    private javax.swing.JComboBox RemPlayNameCmb;
    private javax.swing.JLabel RemPlayNameHeaderLbl;
    private javax.swing.JPanel RemPlayPanel;
    private javax.swing.JLabel RemPlayPlayerHeaderLbl;
    private javax.swing.JLabel RemPlayRemoveHeaderLbl;
    private javax.swing.JComboBox RemPlaySportCmb;
    private javax.swing.JLabel RemPlaySportHeaderLbl;
    private javax.swing.JComboBox RemPlayTeamCmb;
    private javax.swing.JLabel RemPlayTeamHeaderLbl;
    private javax.swing.JTabbedPane RemPlayTeamTourTabbedPane;
    private javax.swing.JComboBox RemPlayTournamentCmb;
    private javax.swing.JLabel RemPlayTournamentHeaderLbl;
    private javax.swing.JPanel RemTeamPanel;
    private javax.swing.JLabel RemTeamRemoveHeaderLbl;
    private javax.swing.JButton RemTourBtn;
    private javax.swing.JPanel RemTourPanel;
    private javax.swing.JLabel RemTourRemoveHeaderLbl;
    private javax.swing.JComboBox RemTourSportCmb;
    private javax.swing.JLabel RemTourSportHeaderLbl;
    private javax.swing.JComboBox RemTourTournamentCmb;
    private javax.swing.JLabel RemTourTournamentHeaderLbl;
    private javax.swing.JLabel RemTourTournamentMainHeaderLbl;
    private javax.swing.JButton RugbyGoToMatchBtn4;
    private javax.swing.JComboBox jComboBox16;
    private javax.swing.JComboBox jComboBox19;
    private javax.swing.JComboBox jComboBox20;
    private javax.swing.JComboBox jComboBox22;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel53;
    // End of variables declaration//GEN-END:variables
}
