/*
 * Sport score preditcion software
 * by Ronnie Muller & Stephan Malan
 */
package com.accupicks.client;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Ronnie
 */
public class RugbyLiveScoreKeepingGameData extends javax.swing.JFrame {

    /**
     * Creates new form RugbyLiveScoreKeepingGameData
     */
    public RugbyLiveScoreKeepingGameData() {
        initComponents();
        
        setLayout(new BorderLayout());
	JLabel background=new JLabel(new ImageIcon("../AccuPicks/src/resources/RugbyBackground.png"));
	add(background);
	background.setLayout(new FlowLayout());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        RugbyHeaderLbl = new javax.swing.JLabel();
        LiveScoreKeepingInfoHeaderLbl = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        StatsTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        BatFirstLbl7 = new javax.swing.JLabel();
        BatFirstLbl10 = new javax.swing.JLabel();
        BowlFirstLbl1 = new javax.swing.JLabel();
        BatFirstLbl12 = new javax.swing.JLabel();
        BatFirstLbl3 = new javax.swing.JLabel();
        BatFirstLbl8 = new javax.swing.JLabel();
        BatFirstLbl6 = new javax.swing.JLabel();
        BatFirstLbl = new javax.swing.JLabel();
        BatFirstLbl11 = new javax.swing.JLabel();
        BatFirstLbl1 = new javax.swing.JLabel();
        BatFirstLbl2 = new javax.swing.JLabel();
        BatFirstLbl5 = new javax.swing.JLabel();
        BatFirstLbl4 = new javax.swing.JLabel();
        BatFirstLbl9 = new javax.swing.JLabel();
        BowlFirstLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BatFirstLbl13 = new javax.swing.JLabel();
        BatFirstLbl14 = new javax.swing.JLabel();
        BowlFirstLbl2 = new javax.swing.JLabel();
        BatFirstLbl15 = new javax.swing.JLabel();
        BatFirstLbl16 = new javax.swing.JLabel();
        BatFirstLbl17 = new javax.swing.JLabel();
        BatFirstLbl18 = new javax.swing.JLabel();
        BatFirstLbl19 = new javax.swing.JLabel();
        BatFirstLbl20 = new javax.swing.JLabel();
        BatFirstLbl21 = new javax.swing.JLabel();
        BatFirstLbl22 = new javax.swing.JLabel();
        BatFirstLbl23 = new javax.swing.JLabel();
        BatFirstLbl24 = new javax.swing.JLabel();
        BatFirstLbl25 = new javax.swing.JLabel();
        BowlFirstLbl3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LiveScoreKeepingInfoHeaderLbl1 = new javax.swing.JLabel();
        LiveScoreKeepingInfoHeaderLbl2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        AccountNameLbl = new javax.swing.JLabel();
        AccuPicksHeaderLbl1 = new javax.swing.JLabel();
        ScoreTimePanel = new javax.swing.JPanel();
        CricketHeaderLbl3 = new javax.swing.JLabel();
        CricketHeaderLbl2 = new javax.swing.JLabel();
        CricketHeaderLbl4 = new javax.swing.JLabel();
        CricketHeaderLbl1 = new javax.swing.JLabel();
        CricketHeaderLbl5 = new javax.swing.JLabel();
        CricketHeaderLbl6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        BackBtn3 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        BackBtn1 = new javax.swing.JButton();
        BackBtn2 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        BackBtn8 = new javax.swing.JButton();
        BackBtn9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(51, 51, 51));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        MainPanel.setOpaque(false);

        RugbyHeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        RugbyHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        RugbyHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        RugbyHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RugbyHeaderLbl.setText("Rugby");

        LiveScoreKeepingInfoHeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        LiveScoreKeepingInfoHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        LiveScoreKeepingInfoHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        LiveScoreKeepingInfoHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LiveScoreKeepingInfoHeaderLbl.setText("Live Score Keeping");

        BackBtn.setBackground(new java.awt.Color(51, 51, 51));
        BackBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setOpaque(false);

        BatFirstLbl7.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl7.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl7.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl7.setText("11.  Winger");

        BatFirstLbl10.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl10.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl10.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl10.setText("13. Center");

        BowlFirstLbl1.setBackground(new java.awt.Color(51, 51, 51));
        BowlFirstLbl1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BowlFirstLbl1.setForeground(new java.awt.Color(255, 255, 255));
        BowlFirstLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BowlFirstLbl1.setText("3. Prop");

        BatFirstLbl12.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl12.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl12.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl12.setText("15. Fback");

        BatFirstLbl3.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl3.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl3.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl3.setText("6. Flanker");

        BatFirstLbl8.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl8.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl8.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl8.setText("10. Fhalf");

        BatFirstLbl6.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl6.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl6.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl6.setText("9. Shalf");

        BatFirstLbl.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl.setText("1. Prop");

        BatFirstLbl11.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl11.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl11.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl11.setText("14. Winger");

        BatFirstLbl1.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl1.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl1.setText("4. Lock");

        BatFirstLbl2.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl2.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl2.setText("5. Lock");

        BatFirstLbl5.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl5.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl5.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl5.setText("8. Eightman");

        BatFirstLbl4.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl4.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl4.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl4.setText("7. Flanker");

        BatFirstLbl9.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl9.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl9.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl9.setText("12. Center");

        BowlFirstLbl.setBackground(new java.awt.Color(51, 51, 51));
        BowlFirstLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BowlFirstLbl.setForeground(new java.awt.Color(255, 255, 255));
        BowlFirstLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BowlFirstLbl.setText("2. Hooker");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BatFirstLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BowlFirstLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BowlFirstLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BatFirstLbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(BatFirstLbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(BatFirstLbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BatFirstLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BatFirstLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BatFirstLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(BatFirstLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(BatFirstLbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(BatFirstLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BatFirstLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(BatFirstLbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(BatFirstLbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BatFirstLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BowlFirstLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BowlFirstLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BatFirstLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatFirstLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BatFirstLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatFirstLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatFirstLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BatFirstLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BatFirstLbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BatFirstLbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BatFirstLbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BatFirstLbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatFirstLbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatFirstLbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        StatsTabbedPane.addTab("Team 1 Team", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setOpaque(false);

        BatFirstLbl13.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl13.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl13.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl13.setText("11.  Winger");

        BatFirstLbl14.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl14.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl14.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl14.setText("13. Center");

        BowlFirstLbl2.setBackground(new java.awt.Color(51, 51, 51));
        BowlFirstLbl2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BowlFirstLbl2.setForeground(new java.awt.Color(255, 255, 255));
        BowlFirstLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BowlFirstLbl2.setText("3. Prop");

        BatFirstLbl15.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl15.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl15.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl15.setText("15. Fback");

        BatFirstLbl16.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl16.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl16.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl16.setText("6. Flanker");

        BatFirstLbl17.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl17.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl17.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl17.setText("10. Fhalf");

        BatFirstLbl18.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl18.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl18.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl18.setText("9. Shalf");

        BatFirstLbl19.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl19.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl19.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl19.setText("1. Prop");

        BatFirstLbl20.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl20.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl20.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl20.setText("14. Winger");

        BatFirstLbl21.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl21.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl21.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl21.setText("4. Lock");

        BatFirstLbl22.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl22.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl22.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl22.setText("5. Lock");

        BatFirstLbl23.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl23.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl23.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl23.setText("8. Eightman");

        BatFirstLbl24.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl24.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl24.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl24.setText("7. Flanker");

        BatFirstLbl25.setBackground(new java.awt.Color(51, 51, 51));
        BatFirstLbl25.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BatFirstLbl25.setForeground(new java.awt.Color(255, 255, 255));
        BatFirstLbl25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BatFirstLbl25.setText("12. Center");

        BowlFirstLbl3.setBackground(new java.awt.Color(51, 51, 51));
        BowlFirstLbl3.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BowlFirstLbl3.setForeground(new java.awt.Color(255, 255, 255));
        BowlFirstLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BowlFirstLbl3.setText("2. Hooker");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BatFirstLbl19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BowlFirstLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BowlFirstLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BatFirstLbl13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(BatFirstLbl15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(BatFirstLbl20, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BatFirstLbl16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BatFirstLbl23, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BatFirstLbl24, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(BatFirstLbl18, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(BatFirstLbl17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(BatFirstLbl21, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BatFirstLbl22, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(BatFirstLbl14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(BatFirstLbl25, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BatFirstLbl19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BowlFirstLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BowlFirstLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BatFirstLbl21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatFirstLbl22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BatFirstLbl16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatFirstLbl23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatFirstLbl24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BatFirstLbl18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BatFirstLbl17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BatFirstLbl25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BatFirstLbl14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BatFirstLbl20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatFirstLbl15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BatFirstLbl13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        StatsTabbedPane.addTab("Team 2 Team", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setOpaque(false);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        LiveScoreKeepingInfoHeaderLbl1.setBackground(new java.awt.Color(51, 51, 51));
        LiveScoreKeepingInfoHeaderLbl1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        LiveScoreKeepingInfoHeaderLbl1.setForeground(new java.awt.Color(255, 255, 255));
        LiveScoreKeepingInfoHeaderLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LiveScoreKeepingInfoHeaderLbl1.setText("Team 1");

        LiveScoreKeepingInfoHeaderLbl2.setBackground(new java.awt.Color(51, 51, 51));
        LiveScoreKeepingInfoHeaderLbl2.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        LiveScoreKeepingInfoHeaderLbl2.setForeground(new java.awt.Color(255, 255, 255));
        LiveScoreKeepingInfoHeaderLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LiveScoreKeepingInfoHeaderLbl2.setText("Team 2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(LiveScoreKeepingInfoHeaderLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LiveScoreKeepingInfoHeaderLbl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LiveScoreKeepingInfoHeaderLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LiveScoreKeepingInfoHeaderLbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        StatsTabbedPane.addTab("Match Stats", jPanel3);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel9.setOpaque(false);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        StatsTabbedPane.addTab("Match Facts", jPanel9);

        AccountNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        AccountNameLbl.setText("AccountName");

        AccuPicksHeaderLbl1.setFont(new java.awt.Font("Algerian", 1, 60)); // NOI18N
        AccuPicksHeaderLbl1.setForeground(new java.awt.Color(255, 255, 255));
        AccuPicksHeaderLbl1.setText("AccuPicks");

        ScoreTimePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        ScoreTimePanel.setOpaque(false);

        CricketHeaderLbl3.setBackground(new java.awt.Color(51, 51, 51));
        CricketHeaderLbl3.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        CricketHeaderLbl3.setForeground(new java.awt.Color(255, 255, 255));
        CricketHeaderLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CricketHeaderLbl3.setText("0");

        CricketHeaderLbl2.setBackground(new java.awt.Color(51, 51, 51));
        CricketHeaderLbl2.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        CricketHeaderLbl2.setForeground(new java.awt.Color(255, 255, 255));
        CricketHeaderLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CricketHeaderLbl2.setText("Team 2");

        CricketHeaderLbl4.setBackground(new java.awt.Color(51, 51, 51));
        CricketHeaderLbl4.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        CricketHeaderLbl4.setForeground(new java.awt.Color(255, 255, 255));
        CricketHeaderLbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CricketHeaderLbl4.setText("0");

        CricketHeaderLbl1.setBackground(new java.awt.Color(51, 51, 51));
        CricketHeaderLbl1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        CricketHeaderLbl1.setForeground(new java.awt.Color(255, 255, 255));
        CricketHeaderLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CricketHeaderLbl1.setText("Team 1");

        CricketHeaderLbl5.setBackground(new java.awt.Color(51, 51, 51));
        CricketHeaderLbl5.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        CricketHeaderLbl5.setForeground(new java.awt.Color(255, 255, 255));
        CricketHeaderLbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CricketHeaderLbl5.setText("40:00");

        CricketHeaderLbl6.setBackground(new java.awt.Color(51, 51, 51));
        CricketHeaderLbl6.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        CricketHeaderLbl6.setForeground(new java.awt.Color(255, 255, 255));
        CricketHeaderLbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CricketHeaderLbl6.setText("Time:");

        javax.swing.GroupLayout ScoreTimePanelLayout = new javax.swing.GroupLayout(ScoreTimePanel);
        ScoreTimePanel.setLayout(ScoreTimePanelLayout);
        ScoreTimePanelLayout.setHorizontalGroup(
            ScoreTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScoreTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ScoreTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CricketHeaderLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CricketHeaderLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CricketHeaderLbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(ScoreTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CricketHeaderLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CricketHeaderLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CricketHeaderLbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ScoreTimePanelLayout.setVerticalGroup(
            ScoreTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScoreTimePanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(ScoreTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CricketHeaderLbl5)
                    .addComponent(CricketHeaderLbl6))
                .addGap(18, 18, 18)
                .addGroup(ScoreTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CricketHeaderLbl1)
                    .addComponent(CricketHeaderLbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ScoreTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CricketHeaderLbl3)
                    .addComponent(CricketHeaderLbl4))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setOpaque(false);

        BackBtn3.setBackground(new java.awt.Color(51, 51, 51));
        BackBtn3.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BackBtn3.setText("Reset Time");
        BackBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtn3ActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(51, 51, 51));
        jToggleButton1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jToggleButton1.setText("Start/Pause Time");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(BackBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel6.setOpaque(false);

        BackBtn1.setBackground(new java.awt.Color(51, 51, 51));
        BackBtn1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BackBtn1.setText("Try");
        BackBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtn1ActionPerformed(evt);
            }
        });

        BackBtn2.setBackground(new java.awt.Color(51, 51, 51));
        BackBtn2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BackBtn2.setText("Penalty");
        BackBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BackBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel10.setOpaque(false);

        BackBtn8.setBackground(new java.awt.Color(51, 51, 51));
        BackBtn8.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BackBtn8.setText("Knock On");
        BackBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtn8ActionPerformed(evt);
            }
        });

        BackBtn9.setBackground(new java.awt.Color(51, 51, 51));
        BackBtn9.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BackBtn9.setText("Line Out");
        BackBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtn9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackBtn8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BackBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScoreTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccuPicksHeaderLbl1)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LiveScoreKeepingInfoHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RugbyHeaderLbl)))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(AccountNameLbl)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccuPicksHeaderLbl1)
                            .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RugbyHeaderLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LiveScoreKeepingInfoHeaderLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccountNameLbl)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(ScoreTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(StatsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        new LiveScoreKeepingHome().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void BackBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtn1ActionPerformed

    private void BackBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtn2ActionPerformed

    private void BackBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtn3ActionPerformed

    private void BackBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtn8ActionPerformed

    private void BackBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtn9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RugbyLiveScoreKeepingGameData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RugbyLiveScoreKeepingGameData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RugbyLiveScoreKeepingGameData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RugbyLiveScoreKeepingGameData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RugbyLiveScoreKeepingGameData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNameLbl;
    private javax.swing.JLabel AccuPicksHeaderLbl1;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton BackBtn1;
    private javax.swing.JButton BackBtn2;
    private javax.swing.JButton BackBtn3;
    private javax.swing.JButton BackBtn4;
    private javax.swing.JButton BackBtn5;
    private javax.swing.JButton BackBtn6;
    private javax.swing.JButton BackBtn7;
    private javax.swing.JButton BackBtn8;
    private javax.swing.JButton BackBtn9;
    private javax.swing.JLabel BatFirstLbl;
    private javax.swing.JLabel BatFirstLbl1;
    private javax.swing.JLabel BatFirstLbl10;
    private javax.swing.JLabel BatFirstLbl11;
    private javax.swing.JLabel BatFirstLbl12;
    private javax.swing.JLabel BatFirstLbl13;
    private javax.swing.JLabel BatFirstLbl14;
    private javax.swing.JLabel BatFirstLbl15;
    private javax.swing.JLabel BatFirstLbl16;
    private javax.swing.JLabel BatFirstLbl17;
    private javax.swing.JLabel BatFirstLbl18;
    private javax.swing.JLabel BatFirstLbl19;
    private javax.swing.JLabel BatFirstLbl2;
    private javax.swing.JLabel BatFirstLbl20;
    private javax.swing.JLabel BatFirstLbl21;
    private javax.swing.JLabel BatFirstLbl22;
    private javax.swing.JLabel BatFirstLbl23;
    private javax.swing.JLabel BatFirstLbl24;
    private javax.swing.JLabel BatFirstLbl25;
    private javax.swing.JLabel BatFirstLbl3;
    private javax.swing.JLabel BatFirstLbl4;
    private javax.swing.JLabel BatFirstLbl5;
    private javax.swing.JLabel BatFirstLbl6;
    private javax.swing.JLabel BatFirstLbl7;
    private javax.swing.JLabel BatFirstLbl8;
    private javax.swing.JLabel BatFirstLbl9;
    private javax.swing.JLabel BowlFirstLbl;
    private javax.swing.JLabel BowlFirstLbl1;
    private javax.swing.JLabel BowlFirstLbl2;
    private javax.swing.JLabel BowlFirstLbl3;
    private javax.swing.JLabel CricketHeaderLbl1;
    private javax.swing.JLabel CricketHeaderLbl2;
    private javax.swing.JLabel CricketHeaderLbl3;
    private javax.swing.JLabel CricketHeaderLbl4;
    private javax.swing.JLabel CricketHeaderLbl5;
    private javax.swing.JLabel CricketHeaderLbl6;
    private javax.swing.JLabel LiveScoreKeepingInfoHeaderLbl;
    private javax.swing.JLabel LiveScoreKeepingInfoHeaderLbl1;
    private javax.swing.JLabel LiveScoreKeepingInfoHeaderLbl2;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel RugbyHeaderLbl;
    private javax.swing.JPanel ScoreTimePanel;
    private javax.swing.JTabbedPane StatsTabbedPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
