/*
 * Sport score preditcion software
 * by Ronnie Muller & Stephan Malan
 */
package com.accupicks.client;

import com.shared.Client;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Ronnie
 */
public class RugbyLiveScoreKeepingGameData extends javax.swing.JFrame {
JLabel backgroundLbl = new JLabel();
private final Client CLIENT;
Timer t = new Timer(1000, new Listener());
int HalfLength = 1;
int Minleft = HalfLength-1;
int Secleft = 59;
static String TeamPlayer;
static String PenaltyOverOrMissed;

    /**
     * Creates new form RugbyLiveScoreKeepingGameData
     */
    public RugbyLiveScoreKeepingGameData(Client client) {
        CLIENT = client;
        initComponents();
        
        setLocationRelativeTo(null);
        AccountNameLbl.setText(CLIENT.getName());
        
        setLayout(new BorderLayout());
        add(backgroundLbl);
        backgroundLbl.setIcon(new ImageIcon(new ImageIcon(AdminHome.class.getResource("/resources/RugbyBackground.png")).getImage().getScaledInstance(1366, 768, java.awt.Image.SCALE_SMOOTH)));
        
    }
    
    class Listener implements ActionListener{    
        public void actionPerformed(ActionEvent a) {           
            if(Minleft>-1){
                TimeLbl.setText(String.format("%02d", Minleft) + ":" + String.format("%02d", Secleft));            
                if(Secleft>0){
                    Secleft--;
                }else{
                    Minleft--;
                    Secleft = 59;
                }
            }else{
                StartPauseBtn.setSelected(false);
            }
        }
    }
    
    private void PointsScored(int Points){
        if(TeamPlayer.substring(0, TeamPlayer.indexOf("#")).matches(Team1Lbl.getText())){
            Team1ScoreLbl.setText(Integer.toString(Integer.parseInt(Team1ScoreLbl.getText())+Points));
        }else{
            Team2ScoreLbl.setText(Integer.toString(Integer.parseInt(Team2ScoreLbl.getText())+Points));
        }
    }
    
    private void TryScored(){
        PointsScored(5);
        //Add to player Stats
    }
    
    private void PenaltyCommited(){
        RugbyLiveScoreKeepingGameDataPenalty dialog = new RugbyLiveScoreKeepingGameDataPenalty(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        if(PenaltyOverOrMissed.substring(0, PenaltyOverOrMissed.indexOf("#")).matches("KickAtGoal$Over")){
            PointsScored(3);
        }
        //Add to player Stats
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        RugbyHeaderLbl = new javax.swing.JLabel();
        LiveScoreKeepingInfoHeaderLbl = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        StatsTabbedPane = new javax.swing.JTabbedPane();
        Team1TeamPanel = new javax.swing.JPanel();
        T1P11Lbl = new javax.swing.JLabel();
        T1P13Lbl = new javax.swing.JLabel();
        T1P3Lbl = new javax.swing.JLabel();
        T1P15Lbl = new javax.swing.JLabel();
        T1P6Lbl = new javax.swing.JLabel();
        T1P10Lbl = new javax.swing.JLabel();
        T1P9Lbl = new javax.swing.JLabel();
        T1P1Lbl = new javax.swing.JLabel();
        T1P14Lbl = new javax.swing.JLabel();
        T1P4Lbl = new javax.swing.JLabel();
        T1P5Lbl = new javax.swing.JLabel();
        T1P8Lbl = new javax.swing.JLabel();
        T1P7Lbl = new javax.swing.JLabel();
        T1P12Lbl = new javax.swing.JLabel();
        T1P2Lbl = new javax.swing.JLabel();
        Team2TeamPanel = new javax.swing.JPanel();
        T2P11Lbl = new javax.swing.JLabel();
        T2P13Lbl = new javax.swing.JLabel();
        T2P3Lbl = new javax.swing.JLabel();
        T2P15Lbl = new javax.swing.JLabel();
        T2P6Lbl = new javax.swing.JLabel();
        T2P10Lbl = new javax.swing.JLabel();
        T2P9Lbl = new javax.swing.JLabel();
        T2P1Lbl = new javax.swing.JLabel();
        T2P14Lbl = new javax.swing.JLabel();
        T2P4Lbl = new javax.swing.JLabel();
        T2P5Lbl = new javax.swing.JLabel();
        T2P8Lbl = new javax.swing.JLabel();
        T2P1Lb7 = new javax.swing.JLabel();
        T2P12Lbl = new javax.swing.JLabel();
        T2P2Lbl = new javax.swing.JLabel();
        MatchStatsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Team2StatsTbl = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        Team1StatsTbl = new javax.swing.JTable();
        Team1MSLbl = new javax.swing.JLabel();
        Team2MSLbl = new javax.swing.JLabel();
        MatchFactsPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        MatchFactsTbl = new javax.swing.JTable();
        AccountNameLbl = new javax.swing.JLabel();
        AccuPicksHeaderLbl1 = new javax.swing.JLabel();
        ScoreTimePanel = new javax.swing.JPanel();
        Team2ScoreLbl = new javax.swing.JLabel();
        Team2Lbl = new javax.swing.JLabel();
        Team1ScoreLbl = new javax.swing.JLabel();
        Team1Lbl = new javax.swing.JLabel();
        TimeLbl = new javax.swing.JLabel();
        TimeHeaderLbl = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ResetTimeBtn = new javax.swing.JButton();
        StartPauseBtn = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        TryBtn = new javax.swing.JButton();
        PenaltyBtn = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        KnockOnBtn = new javax.swing.JButton();
        LineOutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(51, 51, 51));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        MainPanel.setOpaque(false);

        RugbyHeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        RugbyHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        RugbyHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        RugbyHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RugbyHeaderLbl.setText("Rugby");

        LiveScoreKeepingInfoHeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        LiveScoreKeepingInfoHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        LiveScoreKeepingInfoHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        LiveScoreKeepingInfoHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LiveScoreKeepingInfoHeaderLbl.setText("Live Score Keeping");

        BackBtn.setBackground(new java.awt.Color(51, 51, 51));
        BackBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        Team1TeamPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Team1TeamPanel.setOpaque(false);

        T1P11Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T1P11Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T1P11Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T1P11Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1P11Lbl.setText("11.  Winger");

        T1P13Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T1P13Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T1P13Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T1P13Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1P13Lbl.setText("13. Center");

        T1P3Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T1P3Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T1P3Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T1P3Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1P3Lbl.setText("3. Prop");

        T1P15Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T1P15Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T1P15Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T1P15Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1P15Lbl.setText("15. Fback");

        T1P6Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T1P6Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T1P6Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T1P6Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1P6Lbl.setText("6. Flanker");

        T1P10Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T1P10Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T1P10Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T1P10Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1P10Lbl.setText("10. Fhalf");

        T1P9Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T1P9Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T1P9Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T1P9Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1P9Lbl.setText("9. Shalf");

        T1P1Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T1P1Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T1P1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T1P1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1P1Lbl.setText("1. Prop");

        T1P14Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T1P14Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T1P14Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T1P14Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1P14Lbl.setText("14. Winger");

        T1P4Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T1P4Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T1P4Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T1P4Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1P4Lbl.setText("4. Lock");

        T1P5Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T1P5Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T1P5Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T1P5Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1P5Lbl.setText("5. Lock");

        T1P8Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T1P8Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T1P8Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T1P8Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1P8Lbl.setText("8. Eightman");

        T1P7Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T1P7Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T1P7Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T1P7Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1P7Lbl.setText("7. Flanker");

        T1P12Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T1P12Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T1P12Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T1P12Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1P12Lbl.setText("12. Center");

        T1P2Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T1P2Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T1P2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T1P2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1P2Lbl.setText("2. Hooker");

        javax.swing.GroupLayout Team1TeamPanelLayout = new javax.swing.GroupLayout(Team1TeamPanel);
        Team1TeamPanel.setLayout(Team1TeamPanelLayout);
        Team1TeamPanelLayout.setHorizontalGroup(
            Team1TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team1TeamPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Team1TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Team1TeamPanelLayout.createSequentialGroup()
                        .addComponent(T1P1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(T1P2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(T1P3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Team1TeamPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(Team1TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Team1TeamPanelLayout.createSequentialGroup()
                                .addComponent(T1P11Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(T1P15Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(T1P14Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Team1TeamPanelLayout.createSequentialGroup()
                                .addComponent(T1P6Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(T1P8Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(T1P7Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Team1TeamPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(T1P9Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Team1TeamPanelLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(T1P10Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Team1TeamPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(T1P4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(T1P5Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Team1TeamPanelLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(T1P13Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Team1TeamPanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(T1P12Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Team1TeamPanelLayout.setVerticalGroup(
            Team1TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team1TeamPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Team1TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T1P1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T1P3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T1P2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Team1TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T1P4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T1P5Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(Team1TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T1P6Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T1P8Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T1P7Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T1P9Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T1P10Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T1P12Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T1P13Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Team1TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T1P14Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T1P15Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T1P11Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        StatsTabbedPane.addTab("Team 1 Team", Team1TeamPanel);

        Team2TeamPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Team2TeamPanel.setOpaque(false);

        T2P11Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T2P11Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T2P11Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T2P11Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2P11Lbl.setText("11.  Winger");

        T2P13Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T2P13Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T2P13Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T2P13Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2P13Lbl.setText("13. Center");

        T2P3Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T2P3Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T2P3Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T2P3Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2P3Lbl.setText("3. Prop");

        T2P15Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T2P15Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T2P15Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T2P15Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2P15Lbl.setText("15. Fback");

        T2P6Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T2P6Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T2P6Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T2P6Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2P6Lbl.setText("6. Flanker");

        T2P10Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T2P10Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T2P10Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T2P10Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2P10Lbl.setText("10. Fhalf");

        T2P9Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T2P9Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T2P9Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T2P9Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2P9Lbl.setText("9. Shalf");

        T2P1Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T2P1Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T2P1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T2P1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2P1Lbl.setText("1. Prop");

        T2P14Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T2P14Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T2P14Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T2P14Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2P14Lbl.setText("14. Winger");

        T2P4Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T2P4Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T2P4Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T2P4Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2P4Lbl.setText("4. Lock");

        T2P5Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T2P5Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T2P5Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T2P5Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2P5Lbl.setText("5. Lock");

        T2P8Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T2P8Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T2P8Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T2P8Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2P8Lbl.setText("8. Eightman");

        T2P1Lb7.setBackground(new java.awt.Color(51, 51, 51));
        T2P1Lb7.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T2P1Lb7.setForeground(new java.awt.Color(255, 255, 255));
        T2P1Lb7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2P1Lb7.setText("7. Flanker");

        T2P12Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T2P12Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T2P12Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T2P12Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2P12Lbl.setText("12. Center");

        T2P2Lbl.setBackground(new java.awt.Color(51, 51, 51));
        T2P2Lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        T2P2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        T2P2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2P2Lbl.setText("2. Hooker");

        javax.swing.GroupLayout Team2TeamPanelLayout = new javax.swing.GroupLayout(Team2TeamPanel);
        Team2TeamPanel.setLayout(Team2TeamPanelLayout);
        Team2TeamPanelLayout.setHorizontalGroup(
            Team2TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team2TeamPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Team2TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Team2TeamPanelLayout.createSequentialGroup()
                        .addComponent(T2P1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(T2P2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(T2P3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Team2TeamPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(Team2TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Team2TeamPanelLayout.createSequentialGroup()
                                .addComponent(T2P11Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(T2P15Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(T2P14Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Team2TeamPanelLayout.createSequentialGroup()
                                .addComponent(T2P6Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(T2P8Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(T2P1Lb7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Team2TeamPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(T2P9Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Team2TeamPanelLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(T2P10Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Team2TeamPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(T2P4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(T2P5Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Team2TeamPanelLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(T2P13Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Team2TeamPanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(T2P12Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Team2TeamPanelLayout.setVerticalGroup(
            Team2TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team2TeamPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Team2TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T2P1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T2P3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T2P2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Team2TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T2P4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T2P5Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(Team2TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T2P6Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T2P8Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T2P1Lb7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T2P9Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T2P10Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T2P12Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T2P13Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Team2TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T2P14Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T2P15Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T2P11Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        StatsTabbedPane.addTab("Team 2 Team", Team2TeamPanel);

        MatchStatsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        MatchStatsPanel.setOpaque(false);

        Team2StatsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Team2StatsTbl);

        Team1StatsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Team1StatsTbl);

        Team1MSLbl.setBackground(new java.awt.Color(51, 51, 51));
        Team1MSLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Team1MSLbl.setForeground(new java.awt.Color(255, 255, 255));
        Team1MSLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team1MSLbl.setText("Team 1");

        Team2MSLbl.setBackground(new java.awt.Color(51, 51, 51));
        Team2MSLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Team2MSLbl.setForeground(new java.awt.Color(255, 255, 255));
        Team2MSLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team2MSLbl.setText("Team 2");

        javax.swing.GroupLayout MatchStatsPanelLayout = new javax.swing.GroupLayout(MatchStatsPanel);
        MatchStatsPanel.setLayout(MatchStatsPanelLayout);
        MatchStatsPanelLayout.setHorizontalGroup(
            MatchStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatchStatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MatchStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(Team1MSLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Team2MSLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MatchStatsPanelLayout.setVerticalGroup(
            MatchStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatchStatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Team1MSLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Team2MSLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        StatsTabbedPane.addTab("Match Stats", MatchStatsPanel);

        MatchFactsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        MatchFactsPanel.setOpaque(false);

        MatchFactsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(MatchFactsTbl);

        javax.swing.GroupLayout MatchFactsPanelLayout = new javax.swing.GroupLayout(MatchFactsPanel);
        MatchFactsPanel.setLayout(MatchFactsPanelLayout);
        MatchFactsPanelLayout.setHorizontalGroup(
            MatchFactsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatchFactsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );
        MatchFactsPanelLayout.setVerticalGroup(
            MatchFactsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatchFactsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        StatsTabbedPane.addTab("Match Facts", MatchFactsPanel);

        AccountNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        AccountNameLbl.setText("AccountName");

        AccuPicksHeaderLbl1.setFont(new java.awt.Font("Algerian", 1, 60)); // NOI18N
        AccuPicksHeaderLbl1.setForeground(new java.awt.Color(255, 255, 255));
        AccuPicksHeaderLbl1.setText("AccuPicks");

        ScoreTimePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        ScoreTimePanel.setOpaque(false);

        Team2ScoreLbl.setBackground(new java.awt.Color(51, 51, 51));
        Team2ScoreLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        Team2ScoreLbl.setForeground(new java.awt.Color(255, 255, 255));
        Team2ScoreLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team2ScoreLbl.setText("0");

        Team2Lbl.setBackground(new java.awt.Color(51, 51, 51));
        Team2Lbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        Team2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        Team2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team2Lbl.setText("Team 2");

        Team1ScoreLbl.setBackground(new java.awt.Color(51, 51, 51));
        Team1ScoreLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        Team1ScoreLbl.setForeground(new java.awt.Color(255, 255, 255));
        Team1ScoreLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team1ScoreLbl.setText("0");

        Team1Lbl.setBackground(new java.awt.Color(51, 51, 51));
        Team1Lbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        Team1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        Team1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team1Lbl.setText("Team 1");

        TimeLbl.setBackground(new java.awt.Color(51, 51, 51));
        TimeLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        TimeLbl.setForeground(new java.awt.Color(255, 255, 255));
        TimeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimeLbl.setText("40:00");

        TimeHeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        TimeHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        TimeHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        TimeHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimeHeaderLbl.setText("Time:");

        javax.swing.GroupLayout ScoreTimePanelLayout = new javax.swing.GroupLayout(ScoreTimePanel);
        ScoreTimePanel.setLayout(ScoreTimePanelLayout);
        ScoreTimePanelLayout.setHorizontalGroup(
            ScoreTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScoreTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ScoreTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TimeHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Team1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Team1ScoreLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(ScoreTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Team2ScoreLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Team2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TimeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ScoreTimePanelLayout.setVerticalGroup(
            ScoreTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScoreTimePanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(ScoreTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeLbl)
                    .addComponent(TimeHeaderLbl))
                .addGap(18, 18, 18)
                .addGroup(ScoreTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Team1Lbl)
                    .addComponent(Team2Lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ScoreTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Team2ScoreLbl)
                    .addComponent(Team1ScoreLbl))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel5.setOpaque(false);

        ResetTimeBtn.setBackground(new java.awt.Color(51, 51, 51));
        ResetTimeBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        ResetTimeBtn.setText("Reset Time");
        ResetTimeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetTimeBtnActionPerformed(evt);
            }
        });

        StartPauseBtn.setBackground(new java.awt.Color(51, 51, 51));
        StartPauseBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        StartPauseBtn.setText("Start/Pause Time");
        StartPauseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartPauseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StartPauseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetTimeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StartPauseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(ResetTimeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel6.setOpaque(false);

        TryBtn.setBackground(new java.awt.Color(51, 51, 51));
        TryBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        TryBtn.setText("Try");
        TryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TryBtnActionPerformed(evt);
            }
        });

        PenaltyBtn.setBackground(new java.awt.Color(51, 51, 51));
        PenaltyBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        PenaltyBtn.setText("Penalty");
        PenaltyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenaltyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TryBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PenaltyBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PenaltyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel10.setOpaque(false);

        KnockOnBtn.setBackground(new java.awt.Color(51, 51, 51));
        KnockOnBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        KnockOnBtn.setText("Knock On");
        KnockOnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnockOnBtnActionPerformed(evt);
            }
        });

        LineOutBtn.setBackground(new java.awt.Color(51, 51, 51));
        LineOutBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        LineOutBtn.setText("Line Out");
        LineOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KnockOnBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LineOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KnockOnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LineOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScoreTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccuPicksHeaderLbl1)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LiveScoreKeepingInfoHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RugbyHeaderLbl)))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(AccountNameLbl)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccuPicksHeaderLbl1)
                            .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RugbyHeaderLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LiveScoreKeepingInfoHeaderLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccountNameLbl)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(ScoreTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(StatsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        new LiveScoreKeepingHome(CLIENT).setVisible(true);
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void TryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TryBtnActionPerformed
        RugbyLiveScoreKeepingGameDataPlayer dialog = new RugbyLiveScoreKeepingGameDataPlayer(new javax.swing.JFrame(), true, "Choose player who scored the try");
        dialog.setVisible(true);
        TryScored();
    }//GEN-LAST:event_TryBtnActionPerformed

    private void PenaltyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenaltyBtnActionPerformed
        RugbyLiveScoreKeepingGameDataPlayer dialog = new RugbyLiveScoreKeepingGameDataPlayer(new javax.swing.JFrame(), true, "Choose player who committed the penalty");
        dialog.setVisible(true);
        PenaltyCommited();
    }//GEN-LAST:event_PenaltyBtnActionPerformed

    private void ResetTimeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetTimeBtnActionPerformed
        Minleft = Integer.parseInt(JOptionPane.showInputDialog("Min?"));
        Secleft = 59;
        TimeLbl.setText(String.format("%02d", Minleft) + ":" + String.format("%02d", Secleft)); 
    }//GEN-LAST:event_ResetTimeBtnActionPerformed

    private void KnockOnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnockOnBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KnockOnBtnActionPerformed

    private void LineOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineOutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LineOutBtnActionPerformed

    private void StartPauseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartPauseBtnActionPerformed
       if(StartPauseBtn.isSelected()){
            t.start();
        }else{
            t.stop();
        }
    }//GEN-LAST:event_StartPauseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RugbyLiveScoreKeepingGameData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RugbyLiveScoreKeepingGameData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RugbyLiveScoreKeepingGameData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RugbyLiveScoreKeepingGameData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RugbyLiveScoreKeepingGameData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNameLbl;
    private javax.swing.JLabel AccuPicksHeaderLbl1;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton KnockOnBtn;
    private javax.swing.JButton LineOutBtn;
    private javax.swing.JLabel LiveScoreKeepingInfoHeaderLbl;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MatchFactsPanel;
    private javax.swing.JTable MatchFactsTbl;
    private javax.swing.JPanel MatchStatsPanel;
    private javax.swing.JButton PenaltyBtn;
    private javax.swing.JButton ResetTimeBtn;
    private javax.swing.JLabel RugbyHeaderLbl;
    private javax.swing.JPanel ScoreTimePanel;
    private javax.swing.JToggleButton StartPauseBtn;
    private javax.swing.JTabbedPane StatsTabbedPane;
    private javax.swing.JLabel T1P10Lbl;
    private javax.swing.JLabel T1P11Lbl;
    private javax.swing.JLabel T1P12Lbl;
    private javax.swing.JLabel T1P13Lbl;
    private javax.swing.JLabel T1P14Lbl;
    private javax.swing.JLabel T1P15Lbl;
    private javax.swing.JLabel T1P1Lbl;
    private javax.swing.JLabel T1P2Lbl;
    private javax.swing.JLabel T1P3Lbl;
    private javax.swing.JLabel T1P4Lbl;
    private javax.swing.JLabel T1P5Lbl;
    private javax.swing.JLabel T1P6Lbl;
    private javax.swing.JLabel T1P7Lbl;
    private javax.swing.JLabel T1P8Lbl;
    private javax.swing.JLabel T1P9Lbl;
    private javax.swing.JLabel T2P10Lbl;
    private javax.swing.JLabel T2P11Lbl;
    private javax.swing.JLabel T2P12Lbl;
    private javax.swing.JLabel T2P13Lbl;
    private javax.swing.JLabel T2P14Lbl;
    private javax.swing.JLabel T2P15Lbl;
    private javax.swing.JLabel T2P1Lb7;
    private javax.swing.JLabel T2P1Lbl;
    private javax.swing.JLabel T2P2Lbl;
    private javax.swing.JLabel T2P3Lbl;
    private javax.swing.JLabel T2P4Lbl;
    private javax.swing.JLabel T2P5Lbl;
    private javax.swing.JLabel T2P6Lbl;
    private javax.swing.JLabel T2P8Lbl;
    private javax.swing.JLabel T2P9Lbl;
    private javax.swing.JLabel Team1Lbl;
    private javax.swing.JLabel Team1MSLbl;
    private javax.swing.JLabel Team1ScoreLbl;
    private javax.swing.JTable Team1StatsTbl;
    private javax.swing.JPanel Team1TeamPanel;
    private javax.swing.JLabel Team2Lbl;
    private javax.swing.JLabel Team2MSLbl;
    private javax.swing.JLabel Team2ScoreLbl;
    private javax.swing.JTable Team2StatsTbl;
    private javax.swing.JPanel Team2TeamPanel;
    private javax.swing.JLabel TimeHeaderLbl;
    private javax.swing.JLabel TimeLbl;
    private javax.swing.JButton TryBtn;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
