/*
 * Sport score preditcion software
 * by Ronnie Muller & Stephan Malan
 */
package com.accupicks.client;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronnie
 */
public class RugbyLiveScoreKeepingGameDataPenalty extends javax.swing.JDialog {
JLabel backgroundLbl = new JLabel();
    /**
     * Creates new form RugbyLiveScoreKeepingGameDataPenalty
     */
    public RugbyLiveScoreKeepingGameDataPenalty(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        PenaltyBtnGroup.add(PuntRadioBtn);
        PenaltyBtnGroup.add(RunRadioBtn);
        PenaltyBtnGroup.add(ScrumRadioBtn);
        PenaltyBtnGroup.add(KickAtGoalRadioBtn);
        
        KickGoalBtnGroup.add(MissedRadioBtn);
        KickGoalBtnGroup.add(OverRadioBtn);
        
        MissedRadioBtn.setEnabled(false);
        OverRadioBtn.setEnabled(false);
        
        setLayout(new BorderLayout());
        add(backgroundLbl);
        backgroundLbl.setIcon(new ImageIcon(new ImageIcon(AdminHome.class.getResource("/resources/RugbyBackground.png")).getImage().getScaledInstance(1366, 768, java.awt.Image.SCALE_SMOOTH)));
    }
    
    public void EnableDisable(){
        if(PuntRadioBtn.isSelected()){
            MissedRadioBtn.setEnabled(false);
            OverRadioBtn.setEnabled(false);
        }else{
            if(RunRadioBtn.isSelected()){
                MissedRadioBtn.setEnabled(false);
                OverRadioBtn.setEnabled(false);
            }else{
                if(ScrumRadioBtn.isSelected()){
                    MissedRadioBtn.setEnabled(false);
                    OverRadioBtn.setEnabled(false);
                }else{
                    if(KickAtGoalRadioBtn.isSelected()){
                        MissedRadioBtn.setEnabled(true);
                        OverRadioBtn.setEnabled(true);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PenaltyBtnGroup = new javax.swing.ButtonGroup();
        KickGoalBtnGroup = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        RugbyHeaderLbl = new javax.swing.JLabel();
        PenaltyCommitedHeaderLbl = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        AccuPicksHeaderLbl1 = new javax.swing.JLabel();
        TeamsPanel = new javax.swing.JPanel();
        PuntRadioBtn = new javax.swing.JRadioButton();
        RunRadioBtn = new javax.swing.JRadioButton();
        ActionChooseLbl = new javax.swing.JLabel();
        ScrumRadioBtn = new javax.swing.JRadioButton();
        KickAtGoalRadioBtn = new javax.swing.JRadioButton();
        CommitPenaltyBtn = new javax.swing.JButton();
        TeamsPanel1 = new javax.swing.JPanel();
        MissedRadioBtn = new javax.swing.JRadioButton();
        OverRadioBtn = new javax.swing.JRadioButton();
        KickAtGoalHeaderLbl = new javax.swing.JLabel();
        TeamsPanel2 = new javax.swing.JPanel();
        PenaltyOffendedHeaderLbl = new javax.swing.JLabel();
        PenaltyOffendedTxf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(51, 51, 51));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        MainPanel.setOpaque(false);

        RugbyHeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        RugbyHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        RugbyHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        RugbyHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RugbyHeaderLbl.setText("Rugby");

        PenaltyCommitedHeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        PenaltyCommitedHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        PenaltyCommitedHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        PenaltyCommitedHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PenaltyCommitedHeaderLbl.setText("Penalty Commited By Team: Team1, Player: Player1");

        BackBtn.setBackground(new java.awt.Color(51, 51, 51));
        BackBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        AccuPicksHeaderLbl1.setFont(new java.awt.Font("Algerian", 1, 60)); // NOI18N
        AccuPicksHeaderLbl1.setForeground(new java.awt.Color(255, 255, 255));
        AccuPicksHeaderLbl1.setText("AccuPicks");

        TeamsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        TeamsPanel.setOpaque(false);

        PuntRadioBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        PuntRadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        PuntRadioBtn.setText("Punt");
        PuntRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntRadioBtnActionPerformed(evt);
            }
        });

        RunRadioBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        RunRadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        RunRadioBtn.setText("Run");
        RunRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunRadioBtnActionPerformed(evt);
            }
        });

        ActionChooseLbl.setBackground(new java.awt.Color(51, 51, 51));
        ActionChooseLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        ActionChooseLbl.setForeground(new java.awt.Color(255, 255, 255));
        ActionChooseLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ActionChooseLbl.setText("Action Choose By Opposing Team");

        ScrumRadioBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        ScrumRadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        ScrumRadioBtn.setText("Scrum");
        ScrumRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScrumRadioBtnActionPerformed(evt);
            }
        });

        KickAtGoalRadioBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        KickAtGoalRadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        KickAtGoalRadioBtn.setText("Kick At Goal");
        KickAtGoalRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KickAtGoalRadioBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeamsPanelLayout = new javax.swing.GroupLayout(TeamsPanel);
        TeamsPanel.setLayout(TeamsPanelLayout);
        TeamsPanelLayout.setHorizontalGroup(
            TeamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeamsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TeamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PuntRadioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TeamsPanelLayout.createSequentialGroup()
                        .addComponent(ActionChooseLbl)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(RunRadioBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScrumRadioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KickAtGoalRadioBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        TeamsPanelLayout.setVerticalGroup(
            TeamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeamsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ActionChooseLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PuntRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RunRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrumRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KickAtGoalRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CommitPenaltyBtn.setBackground(new java.awt.Color(51, 51, 51));
        CommitPenaltyBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        CommitPenaltyBtn.setText("Commit Penalty");
        CommitPenaltyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommitPenaltyBtnActionPerformed(evt);
            }
        });

        TeamsPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        TeamsPanel1.setOpaque(false);

        MissedRadioBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        MissedRadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        MissedRadioBtn.setText("Missed");
        MissedRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MissedRadioBtnActionPerformed(evt);
            }
        });

        OverRadioBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        OverRadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        OverRadioBtn.setText("over");
        OverRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OverRadioBtnActionPerformed(evt);
            }
        });

        KickAtGoalHeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        KickAtGoalHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        KickAtGoalHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        KickAtGoalHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KickAtGoalHeaderLbl.setText("Kick At Goal");

        javax.swing.GroupLayout TeamsPanel1Layout = new javax.swing.GroupLayout(TeamsPanel1);
        TeamsPanel1.setLayout(TeamsPanel1Layout);
        TeamsPanel1Layout.setHorizontalGroup(
            TeamsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeamsPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TeamsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KickAtGoalHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(MissedRadioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OverRadioBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        TeamsPanel1Layout.setVerticalGroup(
            TeamsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeamsPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KickAtGoalHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MissedRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OverRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TeamsPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        TeamsPanel2.setOpaque(false);

        PenaltyOffendedHeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        PenaltyOffendedHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        PenaltyOffendedHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        PenaltyOffendedHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PenaltyOffendedHeaderLbl.setText("Penalty Offended?");

        PenaltyOffendedTxf.setBackground(new java.awt.Color(51, 51, 51));
        PenaltyOffendedTxf.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        PenaltyOffendedTxf.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout TeamsPanel2Layout = new javax.swing.GroupLayout(TeamsPanel2);
        TeamsPanel2.setLayout(TeamsPanel2Layout);
        TeamsPanel2Layout.setHorizontalGroup(
            TeamsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeamsPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TeamsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PenaltyOffendedHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PenaltyOffendedTxf))
                .addContainerGap())
        );
        TeamsPanel2Layout.setVerticalGroup(
            TeamsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeamsPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PenaltyOffendedHeaderLbl)
                .addGap(18, 18, 18)
                .addComponent(PenaltyOffendedTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CommitPenaltyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BackBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PenaltyCommitedHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addGap(0, 131, Short.MAX_VALUE)
                                .addComponent(AccuPicksHeaderLbl1)
                                .addGap(110, 110, 110))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(RugbyHeaderLbl)
                                .addGap(201, 201, 201))))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TeamsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(TeamsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)))
                        .addGap(18, 18, 18)
                        .addComponent(TeamsPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AccuPicksHeaderLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RugbyHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PenaltyCommitedHeaderLbl)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TeamsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(TeamsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TeamsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)))
                .addComponent(CommitPenaltyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void PuntRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntRadioBtnActionPerformed
        EnableDisable();
    }//GEN-LAST:event_PuntRadioBtnActionPerformed

    private void RunRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunRadioBtnActionPerformed
        EnableDisable();
    }//GEN-LAST:event_RunRadioBtnActionPerformed

    private void CommitPenaltyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommitPenaltyBtnActionPerformed
    String Penalty = PenaltyOffendedTxf.getText();
    
    if(!Penalty.equals("")){
        if(PuntRadioBtn.isSelected()){
            RugbyLiveScoreKeepingGameData.PenaltyOverOrMissed = "Punt$NA#"+Penalty;
        }else{
            if(RunRadioBtn.isSelected()){
                RugbyLiveScoreKeepingGameData.PenaltyOverOrMissed = "Run$NA#"+Penalty;
            }else{
                if(ScrumRadioBtn.isSelected()){
                    RugbyLiveScoreKeepingGameData.PenaltyOverOrMissed = "Scrum$NA#"+Penalty;
                }else{
                    if(KickAtGoalRadioBtn.isSelected()){
                        if(MissedRadioBtn.isSelected()){
                            RugbyLiveScoreKeepingGameData.PenaltyOverOrMissed = "KickAtGoal$Missed#"+Penalty;
                        }else{
                            RugbyLiveScoreKeepingGameData.PenaltyOverOrMissed = "KickAtGoal$Over#"+Penalty;
                        }
                    }
                }
            }
        }
    }else{
        JOptionPane.showMessageDialog(this, "Please Enter The Penalty What Was Commited.");
    }
        dispose();
    }//GEN-LAST:event_CommitPenaltyBtnActionPerformed

    private void ScrumRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScrumRadioBtnActionPerformed
        EnableDisable();
    }//GEN-LAST:event_ScrumRadioBtnActionPerformed

    private void KickAtGoalRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KickAtGoalRadioBtnActionPerformed
        EnableDisable();
    }//GEN-LAST:event_KickAtGoalRadioBtnActionPerformed

    private void MissedRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MissedRadioBtnActionPerformed
    }//GEN-LAST:event_MissedRadioBtnActionPerformed

    private void OverRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OverRadioBtnActionPerformed
    }//GEN-LAST:event_OverRadioBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RugbyLiveScoreKeepingGameDataPenalty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RugbyLiveScoreKeepingGameDataPenalty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RugbyLiveScoreKeepingGameDataPenalty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RugbyLiveScoreKeepingGameDataPenalty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RugbyLiveScoreKeepingGameDataPenalty dialog = new RugbyLiveScoreKeepingGameDataPenalty(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccuPicksHeaderLbl1;
    private javax.swing.JLabel ActionChooseLbl;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton CommitPenaltyBtn;
    private javax.swing.JLabel KickAtGoalHeaderLbl;
    private javax.swing.JRadioButton KickAtGoalRadioBtn;
    private javax.swing.ButtonGroup KickGoalBtnGroup;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JRadioButton MissedRadioBtn;
    private javax.swing.JRadioButton OverRadioBtn;
    private javax.swing.ButtonGroup PenaltyBtnGroup;
    private javax.swing.JLabel PenaltyCommitedHeaderLbl;
    private javax.swing.JLabel PenaltyOffendedHeaderLbl;
    private javax.swing.JTextField PenaltyOffendedTxf;
    private javax.swing.JRadioButton PuntRadioBtn;
    private javax.swing.JLabel RugbyHeaderLbl;
    private javax.swing.JRadioButton RunRadioBtn;
    private javax.swing.JRadioButton ScrumRadioBtn;
    private javax.swing.JPanel TeamsPanel;
    private javax.swing.JPanel TeamsPanel1;
    private javax.swing.JPanel TeamsPanel2;
    // End of variables declaration//GEN-END:variables
}
