/*
 * Sport score preditcion software
 * by Ronnie Muller & Stephan Malan
 */
package com.accupicks.client;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronnie
 */
public class RugbyLiveScoreKeepingGameDataPlayer extends javax.swing.JDialog {
JLabel backgroundLbl = new JLabel();

    /**
     * Creates new form RugbyLiveScoreKeepingGameDataPlayer
     */
    public RugbyLiveScoreKeepingGameDataPlayer(java.awt.Frame parent, boolean modal, String labelstring) {
        super(parent, modal);
        initComponents();
        
        //Add Team Names and players in CMB
        ChooseHeaderLbl.setText(labelstring);
        
        TeamsBtnGroup.add(Team1RadioBtn);
        TeamsBtnGroup.add(Team2RadioBtn);
        Team1PlayersCmb.setEnabled(false);
        Team2PlayersCmb.setEnabled(false);
        
        setLayout(new BorderLayout());
        add(backgroundLbl);
        backgroundLbl.setIcon(new ImageIcon(new ImageIcon(AdminHome.class.getResource("/resources/RugbyBackground.png")).getImage().getScaledInstance(1366, 768, java.awt.Image.SCALE_SMOOTH)));
    }
    
    public void EnableDisable(){
        if(Team1RadioBtn.isSelected()){
            Team1PlayersCmb.setEnabled(true);
            Team2PlayersCmb.setEnabled(false);
        }else{
            Team2PlayersCmb.setEnabled(true);
            Team1PlayersCmb.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TeamsBtnGroup = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        RugbyHeaderLbl = new javax.swing.JLabel();
        ChooseHeaderLbl = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        AccuPicksHeaderLbl1 = new javax.swing.JLabel();
        TeamsPanel = new javax.swing.JPanel();
        Team1RadioBtn = new javax.swing.JRadioButton();
        Team2RadioBtn = new javax.swing.JRadioButton();
        LiveScoreKeepingInfoHeaderLbl1 = new javax.swing.JLabel();
        Team1Panel = new javax.swing.JPanel();
        Team1HeaderLbl = new javax.swing.JLabel();
        Team1PlayersCmb = new javax.swing.JComboBox();
        Team2Panel = new javax.swing.JPanel();
        Team2HeaderLbl = new javax.swing.JLabel();
        Team2PlayersCmb = new javax.swing.JComboBox();
        SelectPlayerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(51, 51, 51));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        MainPanel.setOpaque(false);

        RugbyHeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        RugbyHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        RugbyHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        RugbyHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RugbyHeaderLbl.setText("Rugby");

        ChooseHeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        ChooseHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        ChooseHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        ChooseHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChooseHeaderLbl.setText("Choose Player");

        BackBtn.setBackground(new java.awt.Color(51, 51, 51));
        BackBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        AccuPicksHeaderLbl1.setFont(new java.awt.Font("Algerian", 1, 60)); // NOI18N
        AccuPicksHeaderLbl1.setForeground(new java.awt.Color(255, 255, 255));
        AccuPicksHeaderLbl1.setText("AccuPicks");

        TeamsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        TeamsPanel.setOpaque(false);

        Team1RadioBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Team1RadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        Team1RadioBtn.setText("Team 1");
        Team1RadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team1RadioBtnActionPerformed(evt);
            }
        });

        Team2RadioBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Team2RadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        Team2RadioBtn.setText("Team 2");
        Team2RadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team2RadioBtnActionPerformed(evt);
            }
        });

        LiveScoreKeepingInfoHeaderLbl1.setBackground(new java.awt.Color(51, 51, 51));
        LiveScoreKeepingInfoHeaderLbl1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        LiveScoreKeepingInfoHeaderLbl1.setForeground(new java.awt.Color(255, 255, 255));
        LiveScoreKeepingInfoHeaderLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LiveScoreKeepingInfoHeaderLbl1.setText("Which Team is the Player?");

        javax.swing.GroupLayout TeamsPanelLayout = new javax.swing.GroupLayout(TeamsPanel);
        TeamsPanel.setLayout(TeamsPanelLayout);
        TeamsPanelLayout.setHorizontalGroup(
            TeamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeamsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TeamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Team1RadioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(Team2RadioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(TeamsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LiveScoreKeepingInfoHeaderLbl1)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        TeamsPanelLayout.setVerticalGroup(
            TeamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeamsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LiveScoreKeepingInfoHeaderLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Team1RadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Team2RadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Team1Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Team1Panel.setOpaque(false);

        Team1HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Team1HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Team1HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Team1HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team1HeaderLbl.setText(Team1RadioBtn.getText());

        Team1PlayersCmb.setBackground(new java.awt.Color(51, 51, 51));
        Team1PlayersCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Team1PlayersCmb.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Team1PanelLayout = new javax.swing.GroupLayout(Team1Panel);
        Team1Panel.setLayout(Team1PanelLayout);
        Team1PanelLayout.setHorizontalGroup(
            Team1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Team1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Team1HeaderLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(Team1PlayersCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Team1PanelLayout.setVerticalGroup(
            Team1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Team1HeaderLbl)
                .addGap(18, 18, 18)
                .addComponent(Team1PlayersCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        Team2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Team2Panel.setOpaque(false);

        Team2HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Team2HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        Team2HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Team2HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team2HeaderLbl.setText(Team2RadioBtn.getText());

        Team2PlayersCmb.setBackground(new java.awt.Color(51, 51, 51));
        Team2PlayersCmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Team2PlayersCmb.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Team2PanelLayout = new javax.swing.GroupLayout(Team2Panel);
        Team2Panel.setLayout(Team2PanelLayout);
        Team2PanelLayout.setHorizontalGroup(
            Team2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Team2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Team2HeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Team2PlayersCmb, 0, 240, Short.MAX_VALUE))
                .addContainerGap())
        );
        Team2PanelLayout.setVerticalGroup(
            Team2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Team2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Team2HeaderLbl)
                .addGap(18, 18, 18)
                .addComponent(Team2PlayersCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        SelectPlayerBtn.setBackground(new java.awt.Color(51, 51, 51));
        SelectPlayerBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        SelectPlayerBtn.setText("Select Player");
        SelectPlayerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectPlayerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RugbyHeaderLbl)
                .addGap(213, 213, 213))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(ChooseHeaderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccuPicksHeaderLbl1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addComponent(TeamsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))
                        .addGap(122, 122, 122))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(Team1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(Team2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SelectPlayerBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AccuPicksHeaderLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RugbyHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChooseHeaderLbl)
                .addGap(31, 31, 31)
                .addComponent(TeamsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Team1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Team2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addComponent(SelectPlayerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SelectPlayerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectPlayerBtnActionPerformed
        if(Team1RadioBtn.isSelected()){
            RugbyLiveScoreKeepingGameData.TeamPlayer = Team1HeaderLbl.getText()+"#"+(String)Team1PlayersCmb.getSelectedItem();
        }else{
            if(Team2RadioBtn.isSelected()){
                RugbyLiveScoreKeepingGameData.TeamPlayer = Team2HeaderLbl.getText()+"#"+(String)Team2PlayersCmb.getSelectedItem();
            }else{
                JOptionPane.showMessageDialog(this, "Please select a Team and a Player");
            }
        }
        dispose();
    }//GEN-LAST:event_SelectPlayerBtnActionPerformed

    private void Team1RadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team1RadioBtnActionPerformed
        EnableDisable();
    }//GEN-LAST:event_Team1RadioBtnActionPerformed

    private void Team2RadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team2RadioBtnActionPerformed
        EnableDisable();
    }//GEN-LAST:event_Team2RadioBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RugbyLiveScoreKeepingGameDataPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RugbyLiveScoreKeepingGameDataPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RugbyLiveScoreKeepingGameDataPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RugbyLiveScoreKeepingGameDataPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RugbyLiveScoreKeepingGameDataPlayer dialog = new RugbyLiveScoreKeepingGameDataPlayer(new javax.swing.JFrame(), true, "Choose Player");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccuPicksHeaderLbl1;
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel ChooseHeaderLbl;
    private javax.swing.JLabel LiveScoreKeepingInfoHeaderLbl1;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel RugbyHeaderLbl;
    private javax.swing.JButton SelectPlayerBtn;
    private javax.swing.JLabel Team1HeaderLbl;
    private javax.swing.JPanel Team1Panel;
    private javax.swing.JComboBox Team1PlayersCmb;
    private javax.swing.JRadioButton Team1RadioBtn;
    private javax.swing.JLabel Team2HeaderLbl;
    private javax.swing.JPanel Team2Panel;
    private javax.swing.JComboBox Team2PlayersCmb;
    private javax.swing.JRadioButton Team2RadioBtn;
    private javax.swing.ButtonGroup TeamsBtnGroup;
    private javax.swing.JPanel TeamsPanel;
    // End of variables declaration//GEN-END:variables
}
