/*
 * Sport score preditcion software
 * by Ronnie Muller & Stephan Malan
 */
package com.accupicks.client;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Ronnie
 */
public class RugbySetPositions extends javax.swing.JDialog {

    /**
     * Creates new form RugbySetPositions
     */
    public RugbySetPositions(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLayout(new BorderLayout());
	JLabel background=new JLabel(new ImageIcon("../AccuPicks/src/resources/RugbyBackground.png"));
	add(background);
	background.setLayout(new FlowLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        RugbyHeaderLbl = new javax.swing.JLabel();
        SetPositionsBtn = new javax.swing.JButton();
        Hooker2HeaderLbl = new javax.swing.JLabel();
        Prop1Cmb = new javax.swing.JComboBox();
        Hooker2Cmb = new javax.swing.JComboBox();
        SetPositionsHeaderLbl = new javax.swing.JLabel();
        Prop1HeaderLbl = new javax.swing.JLabel();
        AccuPicksHeaderLbl = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        Prop3Cmb = new javax.swing.JComboBox();
        Prop3HeaderLbl = new javax.swing.JLabel();
        Lock4HeaderLbl = new javax.swing.JLabel();
        Lock4Cmb = new javax.swing.JComboBox();
        Lock5HeaderLbl = new javax.swing.JLabel();
        Lock5Cmb = new javax.swing.JComboBox();
        Flanker6HeaderLbl = new javax.swing.JLabel();
        Flanker6Cmb = new javax.swing.JComboBox();
        Flanker7Cmb = new javax.swing.JComboBox();
        Flanker7HeaderLbl = new javax.swing.JLabel();
        Eigthman8Cmb = new javax.swing.JComboBox();
        Eightman8HeaderLbl = new javax.swing.JLabel();
        ScrumHalf9HeaderLbl = new javax.swing.JLabel();
        Scrumhalf9Cmb = new javax.swing.JComboBox();
        Winger11HeaderLbl = new javax.swing.JLabel();
        Winger11Cmb = new javax.swing.JComboBox();
        FlyHalf10HeaderLbl = new javax.swing.JLabel();
        Flyhalf10Cmb = new javax.swing.JComboBox();
        Centre12Cmb = new javax.swing.JComboBox();
        Centre12HeaderLbl = new javax.swing.JLabel();
        Centre13HeaderLbl = new javax.swing.JLabel();
        Centre13Cmb = new javax.swing.JComboBox();
        Winger14HeaderLbl = new javax.swing.JLabel();
        Winger14Cmb = new javax.swing.JComboBox();
        FullBack15HeaderLbl = new javax.swing.JLabel();
        Fullback15Cmb = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(51, 51, 51));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        MainPanel.setOpaque(false);

        RugbyHeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        RugbyHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        RugbyHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        RugbyHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RugbyHeaderLbl.setText("Rugby");

        SetPositionsBtn.setBackground(new java.awt.Color(51, 51, 51));
        SetPositionsBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        SetPositionsBtn.setForeground(new java.awt.Color(255, 255, 255));
        SetPositionsBtn.setText("Set Positions");
        SetPositionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetPositionsBtnActionPerformed(evt);
            }
        });

        Hooker2HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Hooker2HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Hooker2HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Hooker2HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Hooker2HeaderLbl.setText("2. Hooker");

        Prop1Cmb.setBackground(new java.awt.Color(51, 51, 51));
        Prop1Cmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Prop1Cmb.setForeground(new java.awt.Color(255, 255, 255));

        Hooker2Cmb.setBackground(new java.awt.Color(51, 51, 51));
        Hooker2Cmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Hooker2Cmb.setForeground(new java.awt.Color(255, 255, 255));

        SetPositionsHeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        SetPositionsHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        SetPositionsHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        SetPositionsHeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SetPositionsHeaderLbl.setText("Set Positions");

        Prop1HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Prop1HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Prop1HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Prop1HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Prop1HeaderLbl.setText("1. LooseHeadProp:");

        AccuPicksHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 60)); // NOI18N
        AccuPicksHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        AccuPicksHeaderLbl.setText("AccuPicks");

        BackBtn.setBackground(new java.awt.Color(51, 51, 51));
        BackBtn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        Prop3Cmb.setBackground(new java.awt.Color(51, 51, 51));
        Prop3Cmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Prop3Cmb.setForeground(new java.awt.Color(255, 255, 255));

        Prop3HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Prop3HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Prop3HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Prop3HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Prop3HeaderLbl.setText("3. TightHeadProp:");

        Lock4HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Lock4HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Lock4HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Lock4HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lock4HeaderLbl.setText("4. LeftLock:");

        Lock4Cmb.setBackground(new java.awt.Color(51, 51, 51));
        Lock4Cmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Lock4Cmb.setForeground(new java.awt.Color(255, 255, 255));

        Lock5HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Lock5HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Lock5HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Lock5HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lock5HeaderLbl.setText("5. RightLock:");

        Lock5Cmb.setBackground(new java.awt.Color(51, 51, 51));
        Lock5Cmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Lock5Cmb.setForeground(new java.awt.Color(255, 255, 255));

        Flanker6HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Flanker6HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Flanker6HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Flanker6HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Flanker6HeaderLbl.setText("6. Flanker:");

        Flanker6Cmb.setBackground(new java.awt.Color(51, 51, 51));
        Flanker6Cmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Flanker6Cmb.setForeground(new java.awt.Color(255, 255, 255));

        Flanker7Cmb.setBackground(new java.awt.Color(51, 51, 51));
        Flanker7Cmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Flanker7Cmb.setForeground(new java.awt.Color(255, 255, 255));

        Flanker7HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Flanker7HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Flanker7HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Flanker7HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Flanker7HeaderLbl.setText("7. openSideFlanker");

        Eigthman8Cmb.setBackground(new java.awt.Color(51, 51, 51));
        Eigthman8Cmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Eigthman8Cmb.setForeground(new java.awt.Color(255, 255, 255));

        Eightman8HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Eightman8HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Eightman8HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Eightman8HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Eightman8HeaderLbl.setText("8. Eightman");

        ScrumHalf9HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        ScrumHalf9HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        ScrumHalf9HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        ScrumHalf9HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ScrumHalf9HeaderLbl.setText("9. Scrumhalf");

        Scrumhalf9Cmb.setBackground(new java.awt.Color(51, 51, 51));
        Scrumhalf9Cmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Scrumhalf9Cmb.setForeground(new java.awt.Color(255, 255, 255));

        Winger11HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Winger11HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Winger11HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Winger11HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Winger11HeaderLbl.setText("11. Left Winger");

        Winger11Cmb.setBackground(new java.awt.Color(51, 51, 51));
        Winger11Cmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Winger11Cmb.setForeground(new java.awt.Color(255, 255, 255));

        FlyHalf10HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        FlyHalf10HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        FlyHalf10HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        FlyHalf10HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FlyHalf10HeaderLbl.setText("10. Flyhalf");

        Flyhalf10Cmb.setBackground(new java.awt.Color(51, 51, 51));
        Flyhalf10Cmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Flyhalf10Cmb.setForeground(new java.awt.Color(255, 255, 255));

        Centre12Cmb.setBackground(new java.awt.Color(51, 51, 51));
        Centre12Cmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Centre12Cmb.setForeground(new java.awt.Color(255, 255, 255));

        Centre12HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Centre12HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Centre12HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Centre12HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Centre12HeaderLbl.setText("12. InsideCentre");

        Centre13HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Centre13HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Centre13HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Centre13HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Centre13HeaderLbl.setText("13. OutsideCentre");

        Centre13Cmb.setBackground(new java.awt.Color(51, 51, 51));
        Centre13Cmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Centre13Cmb.setForeground(new java.awt.Color(255, 255, 255));

        Winger14HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        Winger14HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Winger14HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        Winger14HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Winger14HeaderLbl.setText("14. Right Winger");

        Winger14Cmb.setBackground(new java.awt.Color(51, 51, 51));
        Winger14Cmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Winger14Cmb.setForeground(new java.awt.Color(255, 255, 255));

        FullBack15HeaderLbl.setBackground(new java.awt.Color(51, 51, 51));
        FullBack15HeaderLbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        FullBack15HeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        FullBack15HeaderLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FullBack15HeaderLbl.setText("15. Fullback");

        Fullback15Cmb.setBackground(new java.awt.Color(51, 51, 51));
        Fullback15Cmb.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Fullback15Cmb.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AccuPicksHeaderLbl)
                .addGap(497, 497, 497))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(Centre12HeaderLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Centre12Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(371, 371, 371))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(Centre13HeaderLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Centre13Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(Flanker6HeaderLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Flanker6Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(Eightman8HeaderLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Eigthman8Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(Lock4HeaderLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lock4Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(Lock5HeaderLbl)))
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Prop3HeaderLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Prop3Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MainPanelLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(Flanker7HeaderLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Flanker7Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Lock5Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(321, 321, 321)
                                .addComponent(ScrumHalf9HeaderLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Scrumhalf9Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(MainPanelLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(MainPanelLayout.createSequentialGroup()
                                                .addComponent(FullBack15HeaderLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Fullback15Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(MainPanelLayout.createSequentialGroup()
                                                .addComponent(FlyHalf10HeaderLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Flyhalf10Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(MainPanelLayout.createSequentialGroup()
                                            .addGap(459, 459, 459)
                                            .addComponent(Hooker2HeaderLbl)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Hooker2Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(MainPanelLayout.createSequentialGroup()
                                            .addComponent(Prop1HeaderLbl)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Prop1Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(886, 886, 886))))
                                .addGroup(MainPanelLayout.createSequentialGroup()
                                    .addComponent(Winger11HeaderLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Winger11Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Winger14HeaderLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Winger14Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(90, 90, 90))
                                .addGroup(MainPanelLayout.createSequentialGroup()
                                    .addGap(598, 598, 598)
                                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RugbyHeaderLbl)
                                        .addComponent(SetPositionsHeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                    .addComponent(SetPositionsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(AccuPicksHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RugbyHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SetPositionsHeaderLbl)
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Prop1HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Prop1Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Prop3HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Prop3Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hooker2HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hooker2Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lock4HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lock4Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lock5HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lock5Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Flanker6HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Flanker6Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Eightman8HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Eigthman8Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Flanker7HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Flanker7Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ScrumHalf9HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Scrumhalf9Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlyHalf10HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Flyhalf10Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Centre12HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Centre12Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Centre13HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Centre13Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Winger14Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Winger14HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Winger11HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Winger11Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FullBack15HeaderLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fullback15Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SetPositionsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SetPositionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetPositionsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SetPositionsBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        new LiveScoreKeepingHome().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RugbySetPositions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RugbySetPositions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RugbySetPositions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RugbySetPositions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RugbySetPositions dialog = new RugbySetPositions(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccuPicksHeaderLbl;
    private javax.swing.JButton BackBtn;
    private javax.swing.JComboBox Centre12Cmb;
    private javax.swing.JLabel Centre12HeaderLbl;
    private javax.swing.JComboBox Centre13Cmb;
    private javax.swing.JLabel Centre13HeaderLbl;
    private javax.swing.JLabel Eightman8HeaderLbl;
    private javax.swing.JComboBox Eigthman8Cmb;
    private javax.swing.JComboBox Flanker6Cmb;
    private javax.swing.JLabel Flanker6HeaderLbl;
    private javax.swing.JComboBox Flanker7Cmb;
    private javax.swing.JLabel Flanker7HeaderLbl;
    private javax.swing.JLabel FlyHalf10HeaderLbl;
    private javax.swing.JComboBox Flyhalf10Cmb;
    private javax.swing.JLabel FullBack15HeaderLbl;
    private javax.swing.JComboBox Fullback15Cmb;
    private javax.swing.JComboBox Hooker2Cmb;
    private javax.swing.JLabel Hooker2HeaderLbl;
    private javax.swing.JComboBox Lock4Cmb;
    private javax.swing.JLabel Lock4HeaderLbl;
    private javax.swing.JComboBox Lock5Cmb;
    private javax.swing.JLabel Lock5HeaderLbl;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JComboBox Prop1Cmb;
    private javax.swing.JLabel Prop1HeaderLbl;
    private javax.swing.JComboBox Prop3Cmb;
    private javax.swing.JLabel Prop3HeaderLbl;
    private javax.swing.JLabel RugbyHeaderLbl;
    private javax.swing.JLabel ScrumHalf9HeaderLbl;
    private javax.swing.JComboBox Scrumhalf9Cmb;
    private javax.swing.JButton SetPositionsBtn;
    private javax.swing.JLabel SetPositionsHeaderLbl;
    private javax.swing.JComboBox Winger11Cmb;
    private javax.swing.JLabel Winger11HeaderLbl;
    private javax.swing.JComboBox Winger14Cmb;
    private javax.swing.JLabel Winger14HeaderLbl;
    // End of variables declaration//GEN-END:variables
}
