/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.accupicks.client;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import com.shared.Client;

/**
 *
 * @author Ronnie
 */
public class UserHome extends javax.swing.JFrame {
private final Client CLIENT;
JLabel backgroundLbl = new JLabel();
    /**
     * Creates new form UserHome
     */
    public UserHome(Client client) {
        CLIENT = client;
        initComponents();
        
        setLocationRelativeTo(null);
        AccountNameLbl.setText(CLIENT.getName());
        
        setLayout(new BorderLayout());
        add(backgroundLbl);
        backgroundLbl.setIcon(new ImageIcon(new ImageIcon(AdminHome.class.getResource("/resources/HomeBackground1.jpg")).getImage().getScaledInstance(1366, 768, java.awt.Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        HomeHeaderLbl = new javax.swing.JLabel();
        AccountNameLbl = new javax.swing.JLabel();
        MakePicksBtn = new javax.swing.JButton();
        ViewTableForRegisteredTournamentsBtn = new javax.swing.JButton();
        RegisterForTournamentBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        HelpBtn = new javax.swing.JButton();
        ViewProfileInformationBtn = new javax.swing.JButton();
        SearchPlayerBtn = new javax.swing.JButton();
        AccuPicksHeaderLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(51, 51, 51));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        MainPanel.setOpaque(false);

        HomeHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        HomeHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        HomeHeaderLbl.setText("Home");

        AccountNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        AccountNameLbl.setText("AccountName");

        MakePicksBtn.setBackground(new java.awt.Color(51, 51, 51));
        MakePicksBtn.setForeground(new java.awt.Color(255, 255, 255));
        MakePicksBtn.setText("Make Picks");
        MakePicksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakePicksBtnActionPerformed(evt);
            }
        });

        ViewTableForRegisteredTournamentsBtn.setBackground(new java.awt.Color(51, 51, 51));
        ViewTableForRegisteredTournamentsBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewTableForRegisteredTournamentsBtn.setText("View Table for Registered Tournaments");
        ViewTableForRegisteredTournamentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTableForRegisteredTournamentsBtnActionPerformed(evt);
            }
        });

        RegisterForTournamentBtn.setBackground(new java.awt.Color(51, 51, 51));
        RegisterForTournamentBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegisterForTournamentBtn.setText("Register For Tournament");
        RegisterForTournamentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterForTournamentBtnActionPerformed(evt);
            }
        });

        LogOutBtn.setBackground(new java.awt.Color(51, 51, 51));
        LogOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogOutBtn.setText("Log Out");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        HelpBtn.setBackground(new java.awt.Color(51, 51, 51));
        HelpBtn.setForeground(new java.awt.Color(255, 255, 255));
        HelpBtn.setText("Help");
        HelpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpBtnActionPerformed(evt);
            }
        });

        ViewProfileInformationBtn.setBackground(new java.awt.Color(51, 51, 51));
        ViewProfileInformationBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewProfileInformationBtn.setText("View Profile Information");
        ViewProfileInformationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProfileInformationBtnActionPerformed(evt);
            }
        });

        SearchPlayerBtn.setBackground(new java.awt.Color(51, 51, 51));
        SearchPlayerBtn.setForeground(new java.awt.Color(255, 255, 255));
        SearchPlayerBtn.setText("Search Player");
        SearchPlayerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPlayerBtnActionPerformed(evt);
            }
        });

        AccuPicksHeaderLbl.setFont(new java.awt.Font("Algerian", 1, 60)); // NOI18N
        AccuPicksHeaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        AccuPicksHeaderLbl.setText("AccuPicks");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MakePicksBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HelpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegisterForTournamentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ViewProfileInformationBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewTableForRegisteredTournamentsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(241, 241, 241)
                .addComponent(SearchPlayerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(637, 637, 637)
                        .addComponent(AccountNameLbl))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(599, 599, 599)
                        .addComponent(HomeHeaderLbl))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(493, 493, 493)
                        .addComponent(AccuPicksHeaderLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(AccuPicksHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeHeaderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AccountNameLbl)
                .addGap(58, 58, 58)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MakePicksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewTableForRegisteredTournamentsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchPlayerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewProfileInformationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegisterForTournamentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HelpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MakePicksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakePicksBtnActionPerformed

    }//GEN-LAST:event_MakePicksBtnActionPerformed

    private void ViewTableForRegisteredTournamentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTableForRegisteredTournamentsBtnActionPerformed

    }//GEN-LAST:event_ViewTableForRegisteredTournamentsBtnActionPerformed

    private void RegisterForTournamentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterForTournamentBtnActionPerformed

    }//GEN-LAST:event_RegisterForTournamentBtnActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed

    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void HelpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpBtnActionPerformed

    }//GEN-LAST:event_HelpBtnActionPerformed

    private void ViewProfileInformationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProfileInformationBtnActionPerformed

    }//GEN-LAST:event_ViewProfileInformationBtnActionPerformed

    private void SearchPlayerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPlayerBtnActionPerformed

    }//GEN-LAST:event_SearchPlayerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new UserHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNameLbl;
    private javax.swing.JLabel AccuPicksHeaderLbl;
    private javax.swing.JButton HelpBtn;
    private javax.swing.JLabel HomeHeaderLbl;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton MakePicksBtn;
    private javax.swing.JButton RegisterForTournamentBtn;
    private javax.swing.JButton SearchPlayerBtn;
    private javax.swing.JButton ViewProfileInformationBtn;
    private javax.swing.JButton ViewTableForRegisteredTournamentsBtn;
    // End of variables declaration//GEN-END:variables
}
